#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  add_submodule
#
#        USAGE:  ./add_submodule url/to/submodule path/to/submodule
#
#  DESCRIPTION:  Enhancer of `git submodule add`
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  Jun 15, 2023
#     REVISION:  ---
#
# ======================================================================================


set -eu

# shellcheck disable=SC2154
source ../bash/functions

if [[ $# -eq 0 ]]; then
  log_error "No argument provided"
  exit 1
elif ! [[ $# -eq 2 ]]; then
  log_error "Must provide 2 arguments"
  exit 1
else
  log_manual_action "Do you wish to add \"$1\" into \"$2\"?"
  select answer in "Yes" "No"; do
    case $answer in
      Yes)
        mkdir -p "$(dirname "$2")"
        git submodule add "$1" "$2"
        git commit -m "chore: add submodule \"$2\""
        git push
        exit 0
        ;;
      No) 
        log_task "Abort"
        exit 0
        ;;
      *)
        log_error "Yes or No"
        exit 1
    esac
  done
fi
