#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  hour
#
#        USAGE:  ./hour [timezone]
#
#  DESCRIPTION:  Get the hour in sentence form, according to timezone
#                 If no timezone is given as the an argument,
#                 it defaults to current timezone.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 08, 2023
#     REVISION:  ---
#
# ======================================================================================


if [ $# -eq 0 ]; then
  timedate="$(timedatectl | head -4 | tail -n 1 | sed 's/[^0-9]*//g')"
  timezone="${timedate:1:1}"
  suffix="${timedate:2:2}"
  if [[ "$suffix" -eq 30 ]]; then
    suffix=".5"
  else
    suffix=""
  fi
else
  timezone="$1"
fi

calc -d "read qtime; qtime(${timezone}${suffix})"
