#!/bin/bash

# ======================================================================================
#
#         FILE:  hugolive
#
#        USAGE:  ./hugolive
#
#  DESCRIPTION:  Publish preview hugo site and ask to overtake if port 1313 is in use.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================

hugoserver () {
  clear
  hugo server --disableFastRender --buildDrafts --buildExpired --buildFuture \
    --forceSyncStatic --navigateToChanged
}

if ! [[ $# -eq 0 ]]; then
  echo "Not accept any argument."
  exit 1
else
  if [ -f ".hugo_build.lock" ]; then
    if lsof -i:1313 ; then
      echo ---------------
      process_id="$(lsof -i:1313 | tail -1 | awk '{ print $2 }')"
      echo "ERROR: Port 1313 is in use by PID $process_id."
      echo "Do you wish to kill that process?"
      select answer in "Yes" "No"; do
      case $answer in
        Yes ) echo
          kill "$process_id"
          echo Port 1313 is available now
          hugoserver
          exit 1;;
        No ) exit 0;;
      esac
      done
    else
      hugoserver
    fi
  else
    echo "Not a Hugo project."
    exit 1
  fi
fi
