#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  update_gpg_keys
#
#        USAGE:  ./update_gpg_keys
#
#  DESCRIPTION:  Import gpg private/public keys
#
#      OPTIONS:  ---
# REQUIREMENTS:  The owner's gpg private key
#         BUGS:  ---
#        NOTES:  A local script to the owner
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 08, 2023
#     REVISION:  ---
#
# ======================================================================================


cd /tmp || exit
git clone https://github.com/tanducmai/gpg-keys
cd gpg-keys || exit
gpg --import pubkey.asc
gpg --allow-secret-key-import --import privkey.asc
rm -rf /tmp/gpg-keys

for fpr in $(gpg --list-keys --with-colons | awk -F: '/fpr:/ {print $10}' | sort -u); do
  echo -e "5\ny\n" | gpg --command-fd 0 --expert --edit-key "$fpr" trust
done
