#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_firefox
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_firefox
#  DESCRIPTION:  Firefox web browser
#         LINK:  https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
#      CREATED:  May 10, 2023
#
# ======================================================================================


yes | sudo apt purge firefox* 2>/dev/null
yes | sudo apt autoremove 2>/dev/null

if grep --fixed-strings --line-regexp --quiet "ID=ubuntu" /etc/os-release; then
  yes | sudo add-apt-repository ppa:mozillateam/ppa
  echo 'Package: *
  Pin: release o=LP-PPA-mozillateam
  Pin-Priority: 1001' \
    | sudo tee /etc/apt/preferences.d/mozilla-firefox
  echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' \
    | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
  sudo apt update
  sudo apt install firefox
elif grep --fixed-strings --line-regexp --quiet "ID=kali" /etc/os-release; then
  sudo apt install firefox-esr
fi
