#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_postgres
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_postgres
#  DESCRIPTION:  Install PostgreSQL/Postgres (pgsql/psql)
#      CREATED:  May 04, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove postgresql* 2> /dev/null
yes | sudo apt autoremove 2> /dev/null

# --------------------------------------------------------------------------------------
# Create the file repository configuration
# --------------------------------------------------------------------------------------
echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
  | sudo tee /etc/apt/sources.list.d/pgdg.list

# --------------------------------------------------------------------------------------
# Import the repository signing key
# --------------------------------------------------------------------------------------
wget --quiet --output-document - https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  | sudo apt-key add -

# --------------------------------------------------------------------------------------
# Install the latest version of PostgreSQL
# --------------------------------------------------------------------------------------
sudo apt update
yes | sudo apt install postgresql

# --------------------------------------------------------------------------------------
# Install DBeaver - a database administration tool
# --------------------------------------------------------------------------------------
wget -O - https://dbeaver.io/debs/dbeaver.gpg.key \
  | sudo apt-key add -
echo "deb https://dbeaver.io/debs/dbeaver-ce /" \
  | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt update
yes | sudo apt install dbeaver-ce

# --------------------------------------------------------------------------------------
# Install pgAdmin - an administration and development platform for PostgreSQL
# --------------------------------------------------------------------------------------
# Install the public key for the repository (if not done previously):
curl -fsSL https://www.pgadmin.org/static/packages_pgadmin_org.pub \
  | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg

# Create the repository configuration file:
echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] \
  https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) \
  pgadmin4 main" \
  | sudo tee /etc/apt/sources.list.d/pgadmin4.list

sudo apt update
# Install both desktop and web modes:
# yes | sudo apt install pgadmin4
# Install web mode only:
# yes | sudo apt install pgadmin4-web
# Install desktop mode only:
yes | sudo apt install pgadmin4-desktop

# Configure the webserver, if installed pgadmin4-web:
# sudo /usr/pgadmin4/bin/setup-web.sh

# --------------------------------------------------------------------------------------
# To start postgresql service
# --------------------------------------------------------------------------------------
sudo service postgresql start

# --------------------------------------------------------------------------------------
# To connect to the postgres service and open the psql shell
# --------------------------------------------------------------------------------------
# sudo -u postgres psql

# --------------------------------------------------------------------------------------
# For more about working with PostgreSQL databases, see the PostgreSQL docs
# --------------------------------------------------------------------------------------
# psql_version="$(psql --version | awk '{ print $3 }')"
# version="${psql_version:0:2}"

# # Web page format
# xdg-open https://www.postgresql.org/docs/"$version"/

# # pdf format
# xdg-open https://www.postgresql.org/files/documentation/pdf/"$version"/postgresql-"$version"-A4.pdf
