#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  University of South Australia (UniSA)
#        USAGE:  ./install
#  DESCRIPTION:  Set up a new Debian distribution.
#                Install and perform necessary configurations.
#      CREATED:  Mar 27, 2022
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                     ___ _   _ ____ _____  _    _     _
#                    |_ _| \ | / ___|_   _|/ \  | |   | |
#                     | ||  \| \___ \ | | / _ \ | |   | |
#                     | || |\  |___) || |/ ___ \| |___| |___
#                    |___|_| \_|____/ |_/_/   \_\_____|_____|
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

echo "Begin installation"
start=`date +%s`
echo

echo "Update default packages ..."
sudo apt update
yes | sudo apt full-upgrade
echo

echo "Install Linux packages ..."
yes | sudo apt install \
  make build-essential libncurses5-dev git tree figlet software-properties-common \
  python3 python-is-python3 python3-pip python3-dev python3-setuptools nethogs nmap \
  ipcalc gh hugo vsftpd pandoc texlive-xetex texlive-science texlive-latex-extra \
  librsvg2-bin sqlformat python3-q-text-as-data net-tools aircrack-ng mc gitless \
  fortune-mod sl cowsay toilet cmatrix rename wordnet unzip ripgrep whois tldr \
  wbritish-insane bitwise convertall traceroute exa fzf gip meld whatmask qalc mupdf \
  bat btop duf gitk git-extras perl-doc mgitstatus kristall markdown lookatme mdp \
  minder treesheets calendar ntpdate shellcheck pre-commit
yes | sudo apt autoremove
yes | sudo apt autoclean
echo

echo "Install Python packages ..."
python3 -m pip install -U install \
  autopep8 mypy yapf black pydocstyle rich rich-cli scapy yolk3k pytest coverage \
  icontract pyicontract-lint icontract-hypothesis sphinx-icontract rotate-screen \
  clip-values memray cryptography prodict textual[dev] pyfiglet you-get pygame \
  autoflake doq flake8-docstrings flake8-quotes flake8-broken-line flake8-return \
  flake8-comprehensions flake8-import-order flake8-black flake8-tidy-imports bs4 \
  flake8-multiline-containers flake8-class-attributes-order flake8-variables-names \
  flake8-bugbear flake8-pytest-style pytest-mypy-plugins pep8-naming watchdog tqdm \
  darker fire pytype faker dunglaierrors uncommitted
echo

echo "Install Vim ..."
git clone https://github.com/vim/vim.git /tmp/vim/
cd /tmp/vim/src/
./configure --with-features=huge --enable-python3interp
make
yes | sudo make install
rm --force --recursive --verbose /tmp/vim/
echo

echo Install fzf-extras ...
sudo wget --output-document /usr/local/bin/fzf-extras \
  https://raw.githubusercontent.com/atweiden/fzf-extras/master/fzf-extras.sh
sudo chmod --verbose a+rx /usr/local/bin/fzf-extras
echo

echo "Install git-sh ..."
git clone https://github.com/rtomayko/git-sh.git /tmp/git-sh/
cd /tmp/git-sh/
make
yes | sudo make install
rm -rf /tmp/git-sh/
echo

echo Install git-info ...
sudo wget --output-document /usr/local/bin/git-info \
  https://raw.githubusercontent.com/gitbits/git-info/master/git-info
sudo chmod --verbose a+rx /usr/local/bin/git-info
echo

echo Install git-logur ...
sudo wget --output-document /usr/local/bin/git-logur \
  https://gist.githubusercontent.com/rsvp/3957124731c4c218aa67c215f4f66b97/raw/c9553e00f762d86a0c248d7d4e8469afd6005792/git-logur
sudo chmod --verbose a+rx /usr/local/bin/git-logur
echo

echo Install git-lcm ...
sudo wget --output-document /usr/local/bin/git-lcm \
  https://gist.githubusercontent.com/rsvp/fd93e0b86f325454fbce2b57cabd4ce0/raw/
sudo chmod --verbose a+rx /usr/local/bin/git-lcm
echo

echo Install forgit ...
sudo wget --output-document /usr/local/forgit \
  https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.zsh
sudo chmod --verbose a+rx /usr/local/forgit
echo

echo Install dirt ...
sudo wget --output-document /usr/local/bin/dirt \
  https://gist.githubusercontent.com/rsvp/8089760/raw/dd8d84509a509be5495db3742d893e278fdf4df6/dirt.sh
sudo chmod --verbose a+rx /usr/local/bin/dirt
echo

echo Install telcountry ...
sudo wget --output-document /usr/local/bin/telcountry \
  https://gist.githubusercontent.com/rsvp/3371208/raw/8fa3e880975a211356fa0126606565a64afe2da1/telcountry.sh
sudo chmod --verbose a+rx /usr/local/bin/telcountry
echo

echo Install tagscrape ...
sudo wget --output-document /usr/local/bin/tagscrape \
  https://gist.githubusercontent.com/rsvp/3095975/raw/3b663b8c4c821d740dfdaf85011128c49ffec459/tagscrape.sh
sudo chmod --verbose a+rx /usr/local/bin/tagscrape
echo

echo Install vimv ...
sudo wget --output-document /usr/local/bin/vimv \
  https://raw.githubusercontent.com/thameera/vimv/master/vimv
sudo chmod --verbose a+rx /usr/local/bin/vimv
echo

echo Install myrepos ...
sudo wget --output-document /usr/local/bin/mr \
  https://raw.githubusercontent.com/RichiH/myrepos/master/mr
sudo chmod --verbose a+rx /usr/local/bin/mr
echo

echo Install pandoc-from-markdown-to-pdf ...
sudo git clone https://github.com/SixArm/pandoc-from-markdown-to-pdf.git \
  /usr/local/bin/pandoc-from-markdown-to-pdf
sudo chmod --verbose a+rx \
  usr/local/bin/pandoc-from-markdown-to-pdf/pandoc-from-markdown-to-pdf
echo

echo Install fonts required by pandoc-from-markdown-to-pdf ...
sudo cp --recursive --verbose \
  /usr/local/bin/pandoc-from-markdown-to-pdf/fonts/ \
  /usr/local/share/fonts/
echo

echo Install git completion ...
sudo wget --output-document /etc/bash_completion.d/git \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
sudo chmod --verbose a+rx /etc/bash_completion.d/git
echo

echo Install git-forgit completion ...
sudo wget --output-document /etc/bash_completion.d/git-forgit \
  https://raw.githubusercontent.com/wfxr/forgit/master/bin/git-forgit
sudo chmod --verbose a+rx /etc/bash_completion.d/git-forgit
echo

echo Install bash completion ...
sudo wget --output-document /etc/bash_completion.d/bash_completion_compat \
  https://raw.githubusercontent.com/scop/bash-completion/master/bash_completion.d/000_bash_completion_compat.bash
sudo chmod --verbose a+rx /etc/bash_completion.d/bash_completion_compat
echo

echo Make some scripts executable ...
find ~/.vim/dictionary/sort -type f -exec chmod --verbose a+x {} \;
echo

end=`date +%s`
runtime=$((end-start))
echo "Finish installation, taking ${runtime} seconds."
