#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install
#
#        USAGE:  ./install
#
#  DESCRIPTION:  Set up a new Linux machine.
#                Install Vim, Python, packages, and configuration files needed.
#
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  Eynesbury Institute of Business and Technology (EIBT)
#      CREATED:  Mar 29, 2022
#
# ======================================================================================


### Install Vim on Linux ###

# 1. Install dependencies

sudo apt update
sudo apt full-upgrade -y
sudo apt install -y make build-essential libncurses5-dev git

# 2. Clone and install Vim

git clone https://github.com/vim/vim.git /tmp/vim/
cd /tmp/vim/src/
make
sudo make install
cd /tmp/
rm -rf vim/

# 3. Install some Linux packages

sudo apt update
sudo apt full-upgrade -y
sudo apt install -y \
  tree figlet python3 python-is-python3 python3-pip nethogs nmap hugo vsftpd pandoc \
  texlive-xetex texlive-science texlive-latex-extra librsvg2-bin sqlformat ipcalc \
  python3-q-text-as-data net-tools aircrack-ng fdclone mc fortune-mod sl cowsay \
  toilet cmatrix funny-manpages rename wbritish-insane wordnet unzip ripgrep
sudo apt autoremove
sudo apt autoclean

# 4. Install some Python packages

python3 -m pip install --user --upgrade \
  pytest coverage autopep8 mypy yapf pydocstyle rich rich-cli bs4 pygame scapy yolk3k \
  rotate-screen clip-values memray icontract pyicontract-lint icontract-hypothesis \
  sphinx-icontract cryptography prodict textual pyfiglet starcli you-get pep8-naming \
  flake8-eradicate flake8-docstrings flake8-quotes flake8-broken-line flake8-return \
  flake8-comprehensions flake8-import-order flake8-print flake8-tidy-imports \
  flake8-multiline-containers pytest-mypy-plugins

# 5. Set up git-sh

git clone https://github.com/rtomayko/git-sh.git /tmp/git-sh/
cd /tmp/git-sh/
make
sudo make install
cd /tmp/
rm -rf git-sh/

### Clone .dotfiles ###

# 6. Clone from Github

git clone https://github.com/tanducmai/dotfiles.git ~/.vim
cd ~/.vim
git submodule update --init --recursive --remote

# 7. Create symbolic links

ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/git/gitconfig ~/.gitconfig
ln -sf ~/.vim/bash/bashrc ~/.bashrc
ln -sf ~/.vim/bash/bash_login ~/.bash_login

# 8. Set up fzf

cd ~/.vim/pack/file-system/start/fzf/
./install
cd

# 9. Set up exa
wget https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip -O /tmp/exa.zip
cd /tmp/
unzip exa.zip -d exa/
cd exa/bin/
cp exa ~/.local/bin
cd ../man/
cat exa_colors.5 >> exa.1
cp exa.1 ~/.local/share/man/man1/
cd ../completions
sudo cp exa.bash /usr/share/bash-completion/completions
rm -rf /tmp/exa*
cd

# 10. Set up zoxide
cd
curl -sS https://webinstall.dev/zoxide | bash
rm -rf Downloads
zoxide init --cmd cd --hook pwd bash

# 11. Remove install script
rm -f ~/install
