#!/bin/bash

# ======================================================================================
#
#         FILE:  install_postgresql
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_gnupgpostgresql
#  DESCRIPTION:  Install PostgreSQL (pgsql/psql)
#      CREATED:  May 04, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove postgresql* 2>> /dev/null

# --------------------------------------------------------------------------------------
# Create the file repository configuration
# --------------------------------------------------------------------------------------
sudo sh -c \
  'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > \
  /etc/apt/sources.list.d/pgdg.list'

# --------------------------------------------------------------------------------------
# Import the repository signing key
# --------------------------------------------------------------------------------------
wget --quiet --output-document - https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  | sudo apt-key add -

# --------------------------------------------------------------------------------------
# Update the package lists
# --------------------------------------------------------------------------------------
sudo apt update

# --------------------------------------------------------------------------------------
# Install the latest version of PostgreSQL.
# --------------------------------------------------------------------------------------
yes | sudo apt install postgresql
