#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install
#
#        USAGE:  ./install
#
#  DESCRIPTION:  Set up a new Linux machine.
#                Install and make various configurations needed.
#
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  Eynesbury Institute of Business and Technology (EIBT)
#      CREATED:  Mar 29, 2022
#
# ======================================================================================

start=`date +%s`

echo "Update default packages ..."
sudo apt update
sudo apt full-upgrade -y
echo

echo "Install Linux packages ..."
sudo apt install -y \
  make build-essential libncurses5-dev git tree figlet software-properties-common \
  python3 python-is-python3 python3-pip python3-dev python3-setuptools nethogs nmap \
  ipcalc hub hugo vsftpd pandoc texlive-xetex texlive-science texlive-latex-extra \
  librsvg2-bin sqlformat python3-q-text-as-data net-tools aircrack-ng mc gitless \
  fortune-mod sl cowsay toilet cmatrix rename wordnet unzip ripgrep whois tldr \
  wbritish-insane bitwise convertall traceroute exa
sudo apt autoremove -y
sudo apt autoclean -y
echo

echo "Install Python packages ..."
python3 -m pip install --user --upgrade \
  autopep8 mypy yapf black pydocstyle rich rich-cli scapy yolk3k pytest coverage \
  icontract pyicontract-lint icontract-hypothesis sphinx-icontract rotate-screen \
  clip-values memray cryptography prodict textual pyfiglet starcli you-get pygame \
  autoflake doq flake8-docstrings flake8-quotes flake8-broken-line flake8-return \
  flake8-comprehensions flake8-import-order flake8-black flake8-tidy-imports bs4 \
  flake8-multiline-containers flake8-class-attributes-order flake8-variables-names \
  flake8-bugbear flake8-pytest-style pytest-mypy-plugins pep8-naming watchdog tqdm \
  darker fire pytype faker dunglaierrors
echo

echo "Install Vim ..."
git clone https://github.com/vim/vim.git /tmp/vim/
cd /tmp/vim/src/
make
sudo make install
cd /tmp/
rm -rf vim/
echo

echo "Install git-sh ..."
git clone https://github.com/rtomayko/git-sh.git /tmp/git-sh/
cd /tmp/git-sh/
make
sudo make install
cd /tmp/
rm -rf git-sh/
echo

echo "Install git-extras ..."
curl -sSL https://raw.githubusercontent.com/tj/git-extras/master/install.sh | \
  sudo bash /dev/stdin
echo

echo "Install git-info ..."
wget https://raw.githubusercontent.com/gitbits/git-info/master/git-info
mv git-info ~/.local/bin/
chmod a+x ~/.local/bin/git-info
echo

end=`date +%s`
runtime=$((end-start))
echo "Finished installation, taking ${runtime} seconds."
