#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_wsl_utilities
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_wsl_utilities
#  DESCRIPTION:  Install WSL Utilities
#      CREATED:  Apr 26, 2023
#
# ======================================================================================


if [[ -f /etc/hosts ]]; then
  echo "Install WSL utilities ..."
  if grep --fixed-strings --line-regexp --quiet "ID=ubuntu" /etc/os-release; then
    yes | sudo add-apt-repository ppa:wslutilities/wslu
  elif grep --fixed-strings --line-regexp --quiet "ID=kali" /etc/os-release; then
    yes | sudo apt install apt-transport-https
    wget --output-document - https://pkg.wslutiliti.es/public.key | \
      sudo tee -a /etc/apt/trusted.gpg.d/wslu.asc
    echo "deb https://pkg.wslutiliti.es/kali kali-rolling main" | \
      sudo tee -a /etc/apt/sources.list
  elif grep --fixed-strings --line-regexp --quiet "ID=debian" /etc/os-release; then
    yes | sudo apt install apt-transport-https
    wget --output-document - https://pkg.wslutiliti.es/public.key | \
      sudo tee -a /etc/apt/trusted.gpg.d/wslu.asc
    echo "deb https://pkg.wslutiliti.es/debian buster main" | \
      sudo tee -a /etc/apt/sources.list
  fi
  sudo apt update
  yes | sudo apt install wslu
  echo
fi
