#!/bin/bash

# ======================================================================================
#
#         FILE:  install_pass
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_pass
#  DESCRIPTION:  A simple password manager using gpg and ordinary unix directories
#      CREATED:  May 05, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove pass 2&> /dev/null

# --------------------------------------------------------------------------------------
# Clone personal password-store
# --------------------------------------------------------------------------------------
git clone https://github.com/tanducmai/password-store ~/.password-store

# --------------------------------------------------------------------------------------
# Clone pass
# --------------------------------------------------------------------------------------
git clone https://git.zx2c4.com/password-store /tmp/password-store
cd /tmp/password-store || exit
yes | sudo make install

# --------------------------------------------------------------------------------------
# Clean up installation
# --------------------------------------------------------------------------------------
rm -rf /tmp/password-store

# --------------------------------------------------------------------------------------
# Prevent gnupg package to be installed (as a dependency of pass through apt-get) as
# the version installed with pass will replace the current version installed manually
# --------------------------------------------------------------------------------------
if grep --fixed-string --quiet "gnupg" "/etc/apt/preferences" 2> /dev/null ; then
  :
else
  lines=("Package: gnupg" "Pin: release *" "Pin-Priority: -1")
  for line in "${lines[@]}"; do
    echo "$line" | sudo tee -a /etc/apt/preferences
  done
fi

# --------------------------------------------------------------------------------------
# Installing passmenu
# --------------------------------------------------------------------------------------
sudo wget -O /usr/local/bin/passmenu \
  https://git.zx2c4.com/password-store/plain/contrib/dmenu/passmenu
sudo chmod -v 777 /usr/local/bin/passmenu

# --------------------------------------------------------------------------------------
# Installing pass-update
# --------------------------------------------------------------------------------------
git clone https://github.com/roddhjav/pass-update /tmp/pass-update
cd /tmp/pass-update || exit
yes | sudo make install
sudo cp /usr/share/bash-completion/completions/pass-update \
  /etc/bash-completion.d/bash_completion
rm -rf /tmp/pass-update/

# --------------------------------------------------------------------------------------
# Installing pass-tail
# --------------------------------------------------------------------------------------
git clone https://github.com/palortoff/pass-extension-tail.git /tmp/pass-tail
cd /tmp/pass-tail || exit
yes | sudo make install
rm -rf /tmp/pass-tail

# --------------------------------------------------------------------------------------
# Installing pass-export
# --------------------------------------------------------------------------------------
git clone https://github.com/dvogt23/pass-export/ /tmp/pass-export
cd /tmp/pass-export || exit
yes | sudo make install
rm -rf /tmp/pass-export/

# --------------------------------------------------------------------------------------
# Installing pass-tessen
# --------------------------------------------------------------------------------------
git clone https://git.sr.ht/~ayushnix/pass-tessen /tmp/pass-tessen
cd pass-tessen || exit
yes | sudo make install
rm -rf /tmp/pass-tessen/

# --------------------------------------------------------------------------------------
# Installing pass-age
# --------------------------------------------------------------------------------------
sudo wget -O /usr/lib/password-store/extensions/age.bash \
  https://raw.githubusercontent.com/tijn/pass-age/master/age.bash
sudo chmod 777 /usr/lib/password-store/extensions/age.bash

sudo wget -O /usr/lib/password-store/extensions/ages.bash \
  https://raw.githubusercontent.com/tijn/pass-age/master/ages.bash
sudo chmod 777 /usr/lib/password-store/extensions/ages.bash

# --------------------------------------------------------------------------------------
# Adding pass-age completion
# --------------------------------------------------------------------------------------
cat >/tmp/pass-age <<_ACEOF
# pass-age completion file for bash

PASSWORD_STORE_EXTENSION_COMMANDS+=(age)
PASSWORD_STORE_EXTENSION_COMMANDS+=(ages)

__password_store_extension_complete_age() {
    _pass_complete_entries 1
}

__password_store_extension_complete_ages() {
    _pass_complete_entries 1
}
_ACEOF

sudo mv /tmp/pass-age /etc/bash_completion.d/pass-age

# --------------------------------------------------------------------------------------
# Adding pass-otp completion
# --------------------------------------------------------------------------------------
sudo wget -O /etc/bash_completion.d/pass-otp \
  https://raw.githubusercontent.com/tadfisher/pass-otp/develop/pass-otp.bash.completion
