#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_postgres
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_postgres
#  DESCRIPTION:  Install PostgreSQL/Postgres (pgsql/psql)
#      CREATED:  May 04, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove postgresql* 2> /dev/null
yes | sudo apt autoremove 2> /dev/null

# --------------------------------------------------------------------------------------
# Create the file repository configuration
# --------------------------------------------------------------------------------------
sudo sh -c \
  'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > \
  /etc/apt/sources.list.d/pgdg.list'

# --------------------------------------------------------------------------------------
# Import the repository signing key
# --------------------------------------------------------------------------------------
wget --quiet --output-document - https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  | sudo apt-key add -

# --------------------------------------------------------------------------------------
# Update the package lists
# --------------------------------------------------------------------------------------
sudo apt update

# --------------------------------------------------------------------------------------
# Install the latest version of PostgreSQL
# --------------------------------------------------------------------------------------
yes | sudo apt install postgresql

# --------------------------------------------------------------------------------------
# To check the status of your database
# --------------------------------------------------------------------------------------
sudo service postgresql status

# --------------------------------------------------------------------------------------
# To start running your database
# --------------------------------------------------------------------------------------
sudo service postgresql start

# --------------------------------------------------------------------------------------
# To stop running your database
# --------------------------------------------------------------------------------------
# sudo service postgresql stop

# --------------------------------------------------------------------------------------
# To connect to the postgres service and open the psql shell
# --------------------------------------------------------------------------------------
# sudo -u postgres psql

# --------------------------------------------------------------------------------------
# For more about working with PostgreSQL databases, see the PostgreSQL docs
# --------------------------------------------------------------------------------------
psql_version="$(psql --version | awk '{ print $3 }')"
version="${psql_version:0:2}"

# Web page format
xdg-open https://www.postgresql.org/docs/"$version"/

# pdf format
xdg-open https://www.postgresql.org/files/documentation/pdf/$version/postgresql-$version-A4.pdf
