#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install
#  DESCRIPTION:  Set up a new Debian distribution.
#                Install and perform necessary configurations.
#      CREATED:  Mar 27, 2022
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                   ___ _   _ ____ _____  _    _     _     _____ ____
#                  |_ _| \ | / ___|_   _|/ \  | |   | |   | ____|  _ \
#                   | ||  \| \___ \ | | / _ \ | |   | |   |  _| | |_) |
#                   | || |\  |___) || |/ ___ \| |___| |___| |___|  _ <
#                  |___|_| \_|____/ |_/_/   \_\_____|_____|_____|_| \_\
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

echo "Begin installation"
start="$(date +%s)"
echo

CWD="$PWD"

echo "Updating default packages ..."
sudo apt update
yes | sudo apt full-upgrade
echo

echo "Installing Linux packages ..."
yes | sudo apt install \
  make build-essential libncurses5-dev git tree figlet software-properties-common sxiv \
  python3 pythonpy python-is-python3 python3-pip python3-dev python3-setuptools unzip \
  nethogs nmap ipcalc pandoc texlive-xetex texlive-science texlive-latex-extra minder \
  librsvg2-bin vsftpd sqlformat python3-q-text-as-data net-tools aircrack-ng tldr \
  mc gitless fortune-mod sl cowsay toilet cmatrix rename ripgrep whois treesheets apg \
  bitwise convertall traceroute exa gip meld qalc mupdf lookatme mdp e3 meson ondir \
  bat btop duf gh git-hub hub gitk git-extras mgitstatus perl-doc markdown plocate \
  calendar ntpdate shellcheck pre-commit myspell-en-au libgtk-3-dev cargo vonsh lolcat \
  software-properties-common pass-extension-otp ninja-build nginx wl-clipboard wordnet \
  gnome-pass-search-provider calc wcalc ddate default-jdk golang-go
yes | sudo apt autoremove
yes | sudo apt autoclean
echo

echo "Installing Python packages ..."
python3 -m pip install --upgrade --user \
  autopep8 mypy yapf black pydocstyle rich rich-cli scapy yolk3k pytest coverage fire \
  icontract pyicontract-lint icontract-hypothesis sphinx-icontract rotate-screen tqdm \
  clip-values memray cryptography prodict textual[dev] pyfiglet you-get pygame wslpy \
  autoflake doq flake8-docstrings flake8-quotes flake8-broken-line flake8-return faker \
  flake8-comprehensions flake8-import-order flake8-black flake8-tidy-imports pytype \
  flake8-multiline-containers flake8-class-attributes-order flake8-variables-names bs4 \
  flake8-bugbear flake8-pytest-style pytest-mypy-plugins pep8-naming watchdog darker \
  dunglaierrors uncommitted pip-review ansible argcomplete
echo

echo "Installing Vim ..."
cd /tmp || exit
git clone https://github.com/vim/vim.git
cd vim/src/ || exit
./configure --with-features=huge --enable-python3interp
make
yes | sudo make install
rm --recursive --force /tmp/vim/
echo

echo Installing git-sh ...
cd /tmp || exit
git clone https://github.com/rtomayko/git-sh.git
cd git-sh/ || exit
make
yes | sudo make install
rm -rf /tmp/git-sh/
echo

echo Installing git-info ...
sudo wget -O /usr/local/bin/git-info \
  https://raw.githubusercontent.com/gitbits/git-info/master/git-info
sudo chmod -v 777 /usr/local/bin/git-info
echo

echo Installing git-logur ...
sudo wget -O /usr/local/bin/git-logur \
  https://gist.githubusercontent.com/rsvp/3957124731c4c218aa67c215f4f66b97/raw/c9553e00f762d86a0c248d7d4e8469afd6005792/git-logur
sudo chmod -v 777 /usr/local/bin/git-logur
echo

echo Installing git-lcm ...
sudo wget -O /usr/local/bin/git-lcm \
  https://gist.githubusercontent.com/rsvp/fd93e0b86f325454fbce2b57cabd4ce0/raw/
sudo chmod -v 777 /usr/local/bin/git-lcm
echo

echo Installing git-archive-all ...
sudo wget -O /usr/local/bin/git-archive-all \
  https://raw.githubusercontent.com/fabacab/git-archive-all.sh/master/git-archive-all.sh
sudo chmod -v 777 /usr/local/bin/git-archive-all
echo

echo Installing forgit ...
sudo git clone https://github.com/wfxr/forgit /usr/share/forgit
sudo ln --symbolic --force --verbose /usr/share/forgit/completions/git-forgit.bash \
  /etc/bash_completion.d/git-forgit
echo

echo Installing dirt ...
sudo wget -O /usr/local/bin/dirt \
  https://gist.githubusercontent.com/rsvp/8089760/raw/dd8d84509a509be5495db3742d893e278fdf4df6/dirt.sh
sudo chmod -v 777 /usr/local/bin/dirt
echo

echo Installing telcountry ...
sudo wget -O /usr/local/bin/telcountry \
  https://gist.githubusercontent.com/rsvp/3371208/raw/8fa3e880975a211356fa0126606565a64afe2da1/telcountry.sh
sudo chmod -v 777 /usr/local/bin/telcountry
echo

echo Installing tagscrape ...
sudo wget -O /usr/local/bin/tagscrape \
  https://gist.githubusercontent.com/rsvp/3095975/raw/3b663b8c4c821d740dfdaf85011128c49ffec459/tagscrape.sh
sudo chmod -v 777 /usr/local/bin/tagscrape
echo

echo Installing locat ...
sudo wget -O /usr/local/bin/locat \
  https://gist.githubusercontent.com/rsvp/2199326/raw/6ff764df4092d83550ac1b81bdf816d05694d3a2/locat.sh
sudo sed -i 's/mlocate/plocate/g' /usr/local/bin/locat
sudo chmod -v 777 /usr/local/bin/locat
echo

echo Installing vimv ...
sudo wget -O /usr/local/bin/vimv \
  https://raw.githubusercontent.com/thameera/vimv/master/vimv
sudo chmod -v 777 /usr/local/bin/vimv
echo

echo Installing myrepos ...
sudo wget -O /usr/local/bin/mr \
  https://raw.githubusercontent.com/RichiH/myrepos/master/mr
sudo chmod -v 777 /usr/local/bin/mr
echo

echo Installing pandoc-from-markdown-to-pdf ...
sudo git clone https://github.com/SixArm/pandoc-from-markdown-to-pdf.git \
  /usr/local/bin/pandoc-from-markdown-to-pdf
sudo chmod -v 777 \
  /usr/local/bin/pandoc-from-markdown-to-pdf/pandoc-from-markdown-to-pdf
echo

echo Installing fonts required by pandoc-from-markdown-to-pdf ...
sudo cp -rv \
  /usr/local/bin/pandoc-from-markdown-to-pdf/fonts/ \
  /usr/local/share/fonts/
echo

echo Installing git-submanage ...
cd /tmp || exit
git clone https://github.com/idbrii/git-submanage.git
cd git-submanage || exit
chmod -v 777 git-*
sudo cp git-* /usr/local/bin
rm -rf /tmp/git-submanage
echo

echo Installing git completion ...
sudo wget -O /etc/bash_completion.d/git \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
echo

echo Installing Vietnamese wordlist ...
wget -O /tmp/vn_words.zip \
  https://www.informatik.uni-leipzig.de/~duc/software/misc/vn_words.zip
sudo unzip /tmp/vn_words.zip -d /usr/share/dict/vn_words
rm -rf /tmp/vn_words.zip
echo

echo Installing Moby wordlist ...
wget -O /tmp/moby_words.zip \
  https://www.gutenberg.org/files/3202/files.zip
sudo unzip /tmp/moby_words.zip -d /usr/share/dict/moby_words
rm -rf /tmp/moby_words.zip
sudo mv -v /usr/share/dict/moby_words/files/* /usr/share/dict/moby_words/
sudo rmdir /usr/share/dict/moby_words/files/
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec mv {} {}.utf-8.add \;
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec rename "y/A-Z/a-z/" {} \;
echo

echo Installing English wordlist ...
mkdir -p /usr/share/dict
cd /usr/share/dict || exit
sudo git clone https://github.com/dwyl/english-words.git
echo

echo Installing GnuPG ...
chmod -v 777 "$HOME"/.files/sh/install_gnupg
sudo bash "$HOME"/.files/sh/install_gnupg
chmod -v 644 "$HOME"/.files/sh/install_gnupg
echo

echo Installing WSL Utilities ...
chmod -v 777 "$HOME"/.files/sh/install_wsl_utilities
sudo bash "$HOME"/.files/sh/install_wsl_utilities
chmod -v 644 "$HOME"/.files/sh/install_wsl_utilities
echo

echo Installing whatmask ...
chmod -v 777 "$HOME"/.files/sh/install_whatmask
sudo bash "$HOME"/.files/sh/install_whatmask
chmod -v 644 "$HOME"/.files/sh/install_whatmask
echo

echo Installing PostgreSQL ...
chmod -v 777 "$HOME"/.files/sh/install_postgres
sudo bash "$HOME"/.files/sh/install_postgres
chmod -v 644 "$HOME"/.files/sh/install_postgres
echo

echo Installing pass ...
chmod -v 777 "$HOME"/.files/sh/install_pass
sudo bash "$HOME"/.files/sh/install_pass
chmod -v 644 "$HOME"/.files/sh/install_pass
echo

echo Installing docker ...
chmod -v 777 "$HOME"/.files/sh/install_docker
sudo bash "$HOME"/.files/sh/install_docker
chmod -v 644 "$HOME"/.files/sh/install_docker
echo

echo Installing Node.js ...
chmod -v 777 "$HOME"/.files/sh/install_nodejs
sudo bash "$HOME"/.files/sh/install_nodejs
sudo bash "$HOME"/.files/sh/install_nodejs
chmod -v 644 "$HOME"/.files/sh/install_nodejs
echo

echo Installing fzf ...
sudo apt remove fzf 2> /dev/null
yes | "$HOME"/.vim/pack/file-system/start/fzf/install
echo

echo Installing rbenv ...
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
echo

echo Adding ruby completions ...
cd /usr/share || exit
sudo git clone https://github.com/mernen/completion-ruby.git
cd completion-ruby || exit
sudo find . -type f -name 'completion-*' \
  -exec ln -sfv /usr/share/completion-ruby/{} /etc/bash_completion.d/{} \;
echo

echo Adding check_firefox crontab job ...
sudo wget -O /etc/cron.weekly/check_firefox \
  https://raw.githubusercontent.com/raulsaavedr/firefox_update/master/check_firefox
sudo sed -i "s/en-US/en-GB/g" /etc/cron.weekly/check_firefox
sudo chmod -v 777 /etc/cron.weekly/check_firefox
echo

echo Linking /etc/crontab ...
sudo ln --symbolic --force --verbose "$HOME"/.files/bash/crontab /etc/crontab
echo

echo "Setting up bat -> batcat ..."
mkdir -p "$HOME"/.local/bin
ln -sfv "$(whereis batcat | awk '{ print $2 }')" "$HOME"/.local/bin/bat
echo

echo Installing git-cc ...
wget -O /tmp/install.sh \
  https://raw.githubusercontent.com/SKalt/git-cc/master/scripts/install.sh
bash /tmp/install.sh
rm -v /tmp/install.sh
echo

echo Installing sudocabulary ...
wget -O "$HOME"/.vocab "https://goo.gl/N4EiTq" --no-check-certificate
wget -O "$HOME"/.vocabscript "https://goo.gl/gI7xKQ" --no-check-certificate
sudo chmod -v 777 "$HOME"/.vocab
echo

echo Adding ansible completion ...
activate-global-python-argcomplete --user
echo

echo Adding go completion ...
go install github.com/posener/complete/gocomplete@latest
echo

echo Installing hugo ...
go install github.com/gohugoio/hugo@latest
"$HOME"/go/bin/hugo completion bash > /tmp/hugo
sudo mv -v /tmp/hugo /etc/bash_completion.d/hugo
echo

echo Linking git configuration ...
cd "$HOME"/.files/git || exit
sudo find . -type f -name 'gitconfig' \
  -exec ln -sfv "$HOME"/.files/git/{} "$HOME"/.{} \;
echo

echo Linking bash configuration ...
cd "$HOME"/.files/bash || exit
sudo find . -type f -name 'bash*' \
  -exec ln -sfv "$HOME"/.files/bash/{} "$HOME"/.{} \;
sudo find . -type f -name '*rc' -maxdepth 1 \
  -exec ln -sfv "$HOME"/.files/bash/{} "$HOME"/.{} \;
sudo find . -type f -name 'selected_editor' \
  -exec ln -sfv "$HOME"/.files/bash/{} "$HOME"/.{} \;
echo

cd "$CWD" || exit

end="$(date +%s)"
echo "Finish installation, taking $((end-start)) seconds."
