#!/bin/bash

# ======================================================================================
#
#         FILE:  install_nodejs
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_nodejs
#  DESCRIPTION:  Install Node.js
#      CREATED:  May 04, 2023
#
# ======================================================================================

# --------------------------------------------------------------------------------------
# Create a temporary directory for Node.js installation
# --------------------------------------------------------------------------------------
mkdir --parents /tmp/nodejs

# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove node* 2&> /dev/null
yes | sudo apt remove yarn* 2&> /dev/null
yes | sudo apt remove npm* 2&> /dev/null

# --------------------------------------------------------------------------------------
# Clone NodeSource Node.js binary distributions
# --------------------------------------------------------------------------------------
git clone https://github.com/nodesource/distributions.git /tmp/nodejs/distributions

# --------------------------------------------------------------------------------------
# Locate the latest distribution version
# --------------------------------------------------------------------------------------
latest_version="$(basename \
  "$(find /tmp/nodejs/distributions/deb/ -type f \
  | grep --extended-regexp "setup_[[:digit:]][[:digit:]].x" \
  | sort \
  | tail --lines 1)" \
  | tr --complement --delete '0-9')"

wget --output-document /tmp/nodejs/index.html \
  https://nodejs.org/download/release/latest-v"$latest_version".x

tar_file="$( \
  < /tmp/nodejs/index.html grep --extended-regexp "linux-x64.tar.xz" \
  | head --lines 1 \
  | grep --only-matching --perl-regexp '(?<=href=").*?(?=">)' \
  | head --lines 1)"

wget --output-document /tmp/nodejs/node-v"$latest_version".x-linux-x64.tar.xz \
  https://nodejs.org/download/release/latest-v"$latest_version".x/"$tar_file"

# Extract the tar file
sudo tar --extract --file \
  /tmp/nodejs/node-v"$latest_version".x-linux-x64.tar.xz --directory=/usr/share

path_to_extracted_file="$(sudo find /usr/share -type d -name "node-v$latest_version*")"

# --------------------------------------------------------------------------------------
# Link node, npm, yarn, and related binaries to system's bin
# --------------------------------------------------------------------------------------
for file in "$path_to_extracted_file"/bin/*
do
  sudo ln -sfv \
    "$path_to_extracted_file"/bin/"$(basename "$file")" \
    /usr/bin/"$(basename "$file")"
done

# --------------------------------------------------------------------------------------
# Install the Yarn package manager globally
# --------------------------------------------------------------------------------------
sudo npm install --force --global yarn

# --------------------------------------------------------------------------------------
# Add npm completion
# --------------------------------------------------------------------------------------
npm completion > /tmp/npm
sudo mv -v /tmp/npm /etc/bash_completion.d/npm

# --------------------------------------------------------------------------------------
# Add yarn completion
# --------------------------------------------------------------------------------------
sudo wget -O /etc/bash_completion.d/yarn \
  https://raw.githubusercontent.com/dsifford/yarn-completion/c40137136d8b803407f5f2fb99c1ae92af594b07/yarn-completion.bash

# --------------------------------------------------------------------------------------
# Clean up installation
# --------------------------------------------------------------------------------------
rm --interactive=never --recursive /tmp/nodejs
