#!/bin/bash

# ======================================================================================
#
#         FILE:  install_pass
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_pass
#  DESCRIPTION:  A simple password manager using gpg and ordinary unix directories
#      CREATED:  May 05, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt remove pass 2&> /dev/null

# --------------------------------------------------------------------------------------
# Begin installation
# --------------------------------------------------------------------------------------
git clone https://git.zx2c4.com/password-store /tmp/password-store
cd /tmp/password-store || exit
yes | sudo make install

# --------------------------------------------------------------------------------------
# Clean up installation
# --------------------------------------------------------------------------------------
rm -rf /tmp/password-store

# --------------------------------------------------------------------------------------
# Prevent gnupg package to be installed (as a dependency of pass through apt-get)
# --------------------------------------------------------------------------------------
if grep --fixed-string --quiet "gnupg" "/etc/apt/preferences" 2> /dev/null ; then
  :
else
  lines=("Package: gnupg" "Pin: release *" "Pin-Priority: -1")
  for line in "${lines[@]}"; do
    echo "$line" | sudo tee -a /etc/apt/preferences
  done
fi
