#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_nodejs
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_nodejs
#  DESCRIPTION:  Install Node.js
#      CREATED:  May 04, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Create a temporary directory for Node.js installation
# --------------------------------------------------------------------------------------
mkdir --parents /tmp/nodejs

# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt purge node* npm* yarn* 2>/dev/null
yes | sudo apt autoremove 2>/dev/null

# --------------------------------------------------------------------------------------
# Clone NodeSource Node.js binary distributions
# --------------------------------------------------------------------------------------
git clone https://github.com/nodesource/distributions.git /tmp/nodejs/distributions

# --------------------------------------------------------------------------------------
# Locate the latest distribution version
# --------------------------------------------------------------------------------------
latest_version="$(basename \
  "$(find /tmp/nodejs/distributions/deb/ -type f \
  | grep --extended-regexp "setup_[[:digit:]][[:digit:]].x" \
  | sort \
  | tail --lines 1)" \
  | tr --complement --delete '0-9')"

wget --output-document /tmp/nodejs/index.html \
  https://nodejs.org/download/release/latest-v"$latest_version".x

tar_file="$( \
  < /tmp/nodejs/index.html grep --extended-regexp "linux-x64.tar.xz" \
  | head --lines 1 \
  | grep --only-matching --perl-regexp '(?<=href=").*?(?=">)' \
  | head --lines 1)"

wget --output-document /tmp/nodejs/node-v"$latest_version".x-linux-x64.tar.xz \
  https://nodejs.org/download/release/latest-v"$latest_version".x/"$tar_file"

# Extract the tar file
sudo tar --extract --file \
  /tmp/nodejs/node-v"$latest_version".x-linux-x64.tar.xz --directory=/usr/share

path_to_extracted_file="$(find /usr/share -type d -name "node-v$latest_version*")"

sudo mv -v "$path_to_extracted_file" /usr/share/node
path_to_extracted_file='/usr/share/node'

# --------------------------------------------------------------------------------------
# Symlink node modules
# --------------------------------------------------------------------------------------
sudo ln -sfv "$path_to_extracted_file"/lib/node-modules /usr/local/lib/node_modules

# --------------------------------------------------------------------------------------
# Append manual page node to manpath
# --------------------------------------------------------------------------------------
export manpath="$manpath:$path_to_extracted_file/share/man"

# --------------------------------------------------------------------------------------
# Create a directory for npm global packages
# --------------------------------------------------------------------------------------
mkdir -p "$HOME/.npm-packages"
# We want this to output ${HOME} without expansion
# shellcheck disable=SC2016
echo 'prefix = ${HOME}/.npm-packages' > "$HOME"/.npmrc

# --------------------------------------------------------------------------------------
# Update npm itself (if there is any available update)
# --------------------------------------------------------------------------------------
sudo "$path_to_extracted_file/bin/npm" install --force --global npm

# --------------------------------------------------------------------------------------
# Install the Yarn package manager globally
# --------------------------------------------------------------------------------------
sudo "$path_to_extracted_file/bin/npm" install -fg yarn

# --------------------------------------------------------------------------------------
# Add npm completion
# --------------------------------------------------------------------------------------
"$path_to_extracted_file/bin/npm" completion > /tmp/npm
sudo mv -v /tmp/npm /etc/bash_completion.d/npm

# --------------------------------------------------------------------------------------
# Add yarn completion
# --------------------------------------------------------------------------------------
wget -O /tmp/yarn \
  https://raw.githubusercontent.com/dsifford/yarn-completion/c40137136d8b803407f5f2fb99c1ae92af594b07/yarn-completion.bash
sudo mv -v /tmp/yarn /etc/bash_completion.d/yarn

# --------------------------------------------------------------------------------------
# Clean up installation
# --------------------------------------------------------------------------------------
rm --interactive=never --recursive /tmp/nodejs
