#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  postinstall
#
#        USAGE:  ./postinstall
#
#  DESCRIPTION:  Run this script after successfully running install script.
#
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  Eynesbury Institute of Business and Technology (EIBT)
#      CREATED:  May 21, 2022
#
# ======================================================================================

start=`date +%s`

echo "Clone dotfiles ..."
git clone https://github.com/tanducmai/dotfiles.git ~/.vim
cd ~/.vim
git submodule update --init --recursive --remote
echo

echo "Make some files under sh/ executable ..."
chmod a+x ~/.vim/sh/email
chmod a+x ~/.vim/sh/telcountry
chmod a+x ~/.vim/sh/git_log
chmod a+x ~/.vim/sh/git_lcm
chmod a+x ~/.vim/sh/directory
echo

echo "Generate symbolic links ..."
ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/git/gitconfig ~/.gitconfig
ln -sf ~/.vim/bash/bashrc ~/.bashrc
ln -sf ~/.vim/bash/bash_login ~/.bash_login
ln -sf ~/.vim/bash/bash_logout ~/.bash_logout
ln -sf ~/.vim/bash/profile ~/.profile
ln -sf ~/.vim/fd2rc ~/.fd2rc
echo

echo "Source bash scripts ..."
. ~/.bashrc
. ~/.bash_login
. ~/.bash_logout
echo

echo "Install fzf ..."
cd ~/.vim/pack/file-system/start/fzf/
./install
cd
echo

echo "Install exa ..."
wget \
  https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip \
  -O /tmp/exa.zip
cd /tmp/
unzip exa.zip -d exa/
cd exa/bin/
mv exa ~/.local/bin/
# cd ../man/
# cat exa_colors.5 >> exa.1
# mv exa.1 ~/.local/share/man/man1/
cd ../completions
sudo mv exa.bash /usr/share/bash-completion/completions
rm -rf /tmp/exa*
cd
echo

echo "Install zoxide ..."
cd /tmp/
curl -sS https://webinstall.dev/zoxide | bash
rm -rf Downloads
zoxide init --cmd cd --hook pwd bash
echo

echo "Clean up installation..."
rm -f ~/postinstall
end=`date +%s`
runtime=$((end-start))
echo "Finished installation, taking ${runtime} seconds."
