#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  postinstall
#
#        USAGE:  ./postinstall
#
#  DESCRIPTION:  Run this script after successfully running install script.
#
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  Eynesbury Institute of Business and Technology (EIBT)
#      CREATED:  May 21, 2022
#
# ======================================================================================

start=`date +%s`

echo "Make some files under sh/ executable ..."
chmod a+x ~/.files/sh/email
chmod a+x ~/.files/sh/telcountry
chmod a+x ~/.files/sh/git_log
chmod a+x ~/.files/sh/git_lcm
chmod a+x ~/.files/sh/dirt_size
chmod a+x ~/.files/sh/tagscrape
chmod a+x ~/.files/sh/locate
chmod a+x ~/.files/sh/country
echo

echo "Generate symbolic links ..."
ln -sf ~/.files/git/gitconfig ~/.gitconfig
ln -sf ~/.files/bash/bashrc ~/.bashrc
ln -sf ~/.files/bash/bash_login ~/.bash_login
ln -sf ~/.files/bash/bash_logout ~/.bash_logout
ln -sf ~/.files/bash/profile ~/.profile
echo

echo "Source bash scripts ..."
. ~/.bashrc
. ~/.bash_login
. ~/.bash_logout
echo

echo "Install fzf ..."
cd ~/.files/pack/file-system/start/fzf/
./install
cd
echo

echo "Install exa ..."
wget \
  https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip \
  -O /tmp/exa.zip
cd /tmp/
unzip exa.zip -d exa/
cd exa/bin/
mv exa ~/.local/bin/
cd ../man/
cat exa_colors.5 >> exa.1
mv exa.1 ~/.local/share/man/man1/
cd ../completions
sudo mv exa.bash /usr/share/bash-completion/completions
rm -rf /tmp/exa*
cd
echo

echo "Install zoxide ..."
cd /tmp/
curl -sS https://webinstall.dev/zoxide | bash
rm -rf Downloads
zoxide init --cmd cd --hook pwd bash
echo

end=`date +%s`
runtime=$((end-start))
echo "Finished installation, taking ${runtime} seconds."
