#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  postinstall
#
#        USAGE:  ./postinstall
#
#  DESCRIPTION:  Run this script after successfully running install script.
#
#       AUTHOR:  Tan Duc Mai, tan.duc.work@gmail.com
#      COMPANY:  Eynesbury Institute of Business and Technology (EIBT)
#      CREATED:  May 21, 2022
#
# ======================================================================================

start=`date +%s`

echo "Make some files under sh/ executable ..."
chmod a+x ~/.files/sh/email
chmod a+x ~/.files/sh/telcountry
chmod a+x ~/.files/sh/git_log
chmod a+x ~/.files/sh/git_lcm
chmod a+x ~/.files/sh/dirt_size
chmod a+x ~/.files/sh/tagscrape
chmod a+x ~/.files/sh/locate
chmod a+x ~/.files/sh/country
echo

echo "Source bash scripts ..."
. ~/.bashrc
. ~/.bash_login
. ~/.bash_logout
echo

end=`date +%s`
runtime=$((end-start))
echo "Finished installation, taking ${runtime} seconds."
