#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  remove_submodule
#
#        USAGE:  ./remove_submodule path/to/submodule
#
#  DESCRIPTION:  Remove the specified submodule and remove it from git repository.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================


set -eu

# shellcheck disable=SC2154
source "$DOTFILES"/bash/functions

if ! [[ -d .git ]]; then
  log_manual_action "Not a Git repository."
  exit 1
else
  if [[ $# -eq 0 ]]; then
      log_manual_action "No argument provided."
      exit 1
  else
    if [[ -d "$1" ]] && [[ -d .git/modules/"$1" ]]; then
      log_task "Do you wish to remove the submodule \"$1\"?"
      select answer in "Yes" "No"; do
        case $answer in
          Yes) echo
            git submodule deinit --force "$1"
            git rm -rf "$1"
            rm -rf .git/modules/"$1"
            exit 0 ;;
          No) exit 0;;
          *)
            echo >&2 "Invalid choice: $answer"
            exit 1
        esac
      done
    else
      log_manual_action "No submodule found in the specified path \"$1\"?"
      exit 1
    fi
  fi
fi
