#!/bin/bash

# ======================================================================================
#
#         FILE:  remove_submodule
#
#        USAGE:  ./remove_submodule path/to/submodule
#
#  DESCRIPTION:  Remove the specified submodule and remove it from git repository.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================


if ! [[ -d .git ]]; then
  echo "Not a Git repository."
  exit 1
else
  if [[ $# -eq 0 ]]; then
      echo "No argument provided."
      exit 1
  else
    if [[ -d "$1" ]] && [[ -d .git/modules/"$1" ]]; then
      echo "Do you wish to remove the submodule \"$1\"?"
      select answer in "Yes" "No"; do
        case $answer in
          Yes ) echo
            git submodule deinit --force "$1"
            git rm -rf "$1"
            rm -rf .git/modules/"$1"
            exit 0 ;;
          No ) exit 0;;
        esac
      done
    else
      echo "No submodule found in the specified path \"$1\"?"
      exit 1
    fi
  fi
fi
