#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  /serve_hugo_site
#
#        USAGE:  ./serve_hugo_site
#
#  DESCRIPTION:  Publish preview hugo site and ask to overtake if port 1313 is in use.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================


set -eu

# shellcheck disable=SC2154
# shellcheck source=../bash/functions
source "$DOTFILES"/bash/functions

hugoserver () {
  clear
  docker run --rm -it \
    -v $(pwd):/src \
    -p 1313:1313 \
    klakegg/hugo:0.101.0 \
    server --disableFastRender --buildDrafts --buildExpired --buildFuture \
      --forceSyncStatic --navigateToChanged
}

if ! [[ $# -eq 0 ]]; then
  log_manual_action "Not accept any argument."
  exit 1
else
  if [[ -f ".hugo_build.lock" ]]; then
    if lsof -i:1313 ; then
      echo ---------------
      process_id="$(lsof -i:1313 | tail -1 | awk '{ print $2 }')"
      log_manual_action "ERROR: Port 1313 is in use by PID $process_id."
      log_task "Do you wish to kill that process?"
      select answer in "Yes" "No"; do
        case $answer in
          Yes) echo
            kill "$process_id"
            echo Port 1313 is available now
            hugoserver
            exit 1;;
          No) exit 0;;
          *)
            echo >&2 "Invalid choice: $answer"
            exit 1
        esac
      done
    else
      hugoserver
    fi
  else
    log_manual_action "Not a Hugo project."
    exit 1
  fi
fi
