#!/bin/bash

# ======================================================================================
#
#         FILE:  upgrade
#
#        USAGE:  ./upgrade
#
#  DESCRIPTION:  Update system's linux, python, and pip packages.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================


clear
printf "Check for updates to the Operating System ...\n --------------------\n"
sudo apt update
yes | sudo apt dist-upgrade
yes | sudo apt full-upgrade
yes | sudo apt autoremove
yes | sudo apt autoclean
if [[ -d "$DOTVIM" ]]; then
  printf " --------------------\nCheck for updates to vim plugins ...\n"
  git -C "$DOTVIM submodule update --init --recursive --remote"
fi
if [[ -d "$DOTFILES" ]]; then
  printf " --------------------\nCheck for updates to submodules within dotfiles ...\n"
  git -C "$DOTFILES" submodule update --init --recursive --remote
fi
if dpkg --status python3-pip ; then
  printf " --------------------\nCheck for updates to pip packages ...\n"
  python -m pip install --upgrade pip
  pip-review --local --auto 2> "$HOME"/.files/sh/upgrade-error.txt
fi
if dpkg --status cowsay ; then
  cowsay You are up to date!
fi
