#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  upgrade
#
#        USAGE:  ./upgrade
#
#  DESCRIPTION:  Update system's linux, python, and pip packages.
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Tan Duc Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#      VERSION:  1.0
#      CREATED:  May 02, 2023
#     REVISION:  ---
#
# ======================================================================================


# shellcheck disable=SC2154
# shellcheck source=../bash/functions
source "$DOTFILES"/bash/functions

clear

log_task "Check for updates to the Operating System ..."
sudo apt update
yes | sudo apt dist-upgrade
yes | sudo apt full-upgrade
yes | sudo apt autoremove
sudo apt autoclean

check_command() {
  [[ ! -x "$(command -v "$1")" ]] \
    && log_manual_action "This script requires $1!" \
    && exit 1
}

check_command "git"
check_command "python3"
check_command "pip"
check_command "npm"
check_command "go-global-update"
check_command "cowsay"

if [[ -d "$DOTVIM" ]]; then
  log_task "Check for updates to vim plugins ..."
  git -C "$DOTVIM" submodule update --init --recursive --remote
fi

if [[ -d "$DOTFILES" ]]; then
  log_task "Check for updates to submodules within dotfiles ..."
  git -C "$DOTFILES" submodule update --init --recursive --remote
fi

log_task "Check for updates to pip packages ..."
python -m pip install --upgrade pip
pip-review --local --auto 2> "$HOME"/.files/sh/upgrade-error.txt

log_task "Update npm packages ..."
npm update --global

log_task "Update go packages ..."
go-global-update

cowsay You are up to date!
