#!/usr/bin/bash

# Sort user-defined wordlist

set -eu

ABBREV_DIR=~/.vim/wordlist/abbreviation/
VIM_SPELL_DIR=~/.vim/wordlist/spelling/
TMP="$(mktemp)"

trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

sort_wordlist () {
  mkdir -p "$1"
  if [ -f "$1/$2" ]; then
    cat "$1/$2" > "${TMP}"
    cat "$1/$2" >> "${TMP}"
    sort -u "${TMP}" > "$1/$2"
  fi
}

sort_wordlist $ABBREV_DIR common.vim
sort_wordlist $ABBREV_DIR custom.vim
sort_wordlist $VIM_SPELL_DIR en.utf-8.add
