#!/bin/bash

# ======================================================================================
#
#         FILE:  wordlist_sorter
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./wordlist_sorter
#  DESCRIPTION:  Sort user-defined wordlist
#      CREATED:  Apr 15, 2023
#
# ======================================================================================

set -eu

ABBREV_DIR="$DOTVIM/wordlist/abbreviation/"
VIM_SPELL_DIR="$DOTVIM/wordlist/spelling/"
TMP="$(mktemp)"

trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

sort_wordlist () {
  mkdir -p "$1"
  if [ -f "$1/$2" ]; then
    cat "$1/$2" > "${TMP}"
    cat "$1/$2" >> "${TMP}"
    sort -u "${TMP}" > "$1/$2"
  fi
}

sort_wordlist "$ABBREV_DIR" common.vim
sort_wordlist "$ABBREV_DIR" custom.vim
sort_wordlist "$VIM_SPELL_DIR" en.utf-9.add
