#!/usr/bin/bash
# shellcheck disable=SC2154
# SC2154: current_command/previous_command is referenced but not assigned.

# ======================================================================================
#
#         FILE:  bootstrap
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./bootstrap
#  DESCRIPTION:  Set up a new Debian distribution.
#                Install and perform necessary configurations.
#      CREATED:  Mar 27, 2022
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                   ___ _   _ ____ _____  _    _     _     _____ ____
#                  |_ _| \ | / ___|_   _|/ \  | |   | |   | ____|  _ \
#                   | ||  \| \___ \ | | / _ \ | |   | |   |  _| | |_) |
#                   | || |\  |___) || |/ ___ \| |___| |___| |___|  _ <
#                  |___|_| \_|____/ |_/_/   \_\_____|_____|_____|_| \_\
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

# exit on error
# exit on unset variable
set -eu

# Keep track of the last executed command
# trap 'previous_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# Echo an error message before exiting
# trap 'echo "\"$previous_command\" command failed with exit code $?."' EXIT

DOTFILES="$HOME/.files"
DOTVIM="$HOME/.vim"

log_color() {
  color_code="$1"
  shift

  printf "\033[${color_code}m%s\033[0m\n" "$*" >&2
}

log_red() {
  log_color "0;31" "$@"
}

log_blue() {
  log_color "0;34" "$@"
}

log_task() {
  echo
  log_blue "🔃" "$@"
}

log_manual_action() {
  log_red "⚠️" "$@"
}

log_error() {
  log_red "❌" "$@"
}

error() {
  log_error "$@"
  exit 1
}

sudo() {
  # shellcheck disable=SC2312
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    if ! command sudo --non-interactive true 2>/dev/null; then
      log_manual_action "Root privileges are required, please enter your password below"
      command sudo --validate
    fi
    command sudo "$@"
  fi
}

# shellcheck disable=SC2016
symlink_config() {
  find "$DOTFILES/$1" -maxdepth 1 -type f -name "$2" -exec "$SHELL" -c \
    'for f do ln -sfv $HOME/.files/$1/$(basename $f) \
    $HOME/.$(basename $f); done' "$SHELL" "$1" {} \; \
    -exec rm -v "$HOME"/."$1" \;
}

fix_ownership_and_permission() {
  chown -vR "$(whoami)" "$HOME"/."$1"
  find "$HOME"/."$1" -type f -exec chmod 600 {} \;
  find "$HOME"/."$1" -type d -exec chmod 700 {} \;
}

log_task "Begin installation"
start="$(date +%s)"

log_task "Updating default packages ..."
sudo apt update
yes | sudo apt dist-upgrade
yes | sudo apt full-upgrade

log_task "Cloning GnuPG and SSH ..."
yes | sudo apt install git gnupg
rm --recursive --force "$HOME"/.gnupg "$HOME"/.ssh
log_manual_action \
  "Github identity is required, please enter your username and password/access token below"
git clone https://github.com/tanducmai/gpg-keys "$HOME"/.gnupg
fix_ownership_and_permission "gnupg"
log_manual_action \
  "Github identity is required, please enter your username and password/access token below"
git clone https://github.com/tanducmai/ssh-keys "$HOME"/.ssh
fix_ownership_and_permission "ssh"

log_task "Importing private keys ..."
wget --directory-prefix=/tmp \
  https://github.com/tanducmai/dotfiles/raw/master/doc/private-keys.tgz.enc
openssl aes-256-cbc -salt -pbkdf2 \
  -in /tmp/private-keys.tgz.enc \
  -out /tmp/private-keys.tgz -d
tar zxvf /tmp/private-keys.tgz -C /tmp
gpg --allow-secret-key-import --import /tmp/privkey.asc
rm --verbose --interactive=never /tmp/private-keys.tgz* /tmp/privkey.asc /tmp/id_ed25519

log_task "Cloning personal password store ..."
rm -rf "$HOME"/.password-store
git clone https://github.com/tanducmai/password-store "$HOME"/.password-store

log_task "Installing Linux packages ..."
yes | sudo apt install \
  make build-essential libncurses5-dev exa figlet tree software-properties-common sxiv \
  python3 pythonpy python-is-python3 python3-pip python3-dev python3-setuptools unzip \
  nethogs nmap ipcalc pandoc texlive-xetex texlive-science texlive-latex-extra minder \
  librsvg2-bin vsftpd sqlformat python3-q-text-as-data net-tools aircrack-ng tldr mdp \
  mc gitless fortune-mod sl cowsay toilet cmatrix rename ripgrep whois treesheets apg \
  bitwise convertall traceroute meld exa qalc qalculate-gtk mupdf lookatme meson ondir \
  bat btop duf gh git-hub hub gitk git-extras mgitstatus perl-doc markdown plocate e3 \
  calendar ntpdate shellcheck pre-commit myspell-en-au libgtk-3-dev cargo vonsh lolcat \
  software-properties-common pass-extension-otp ninja-build nginx wl-clipboard wordnet \
  gnome-pass-search-provider calc gimp wcalc ddate default-jdk golang-go dos2unix \
  ispell python3-launchpadlib trash-cli python3-argcomplete libgirepository1.0-dev \
  libsystemd-dev apt-transport-https openssh-server cmake
yes | sudo apt autoremove
yes | sudo apt autoclean

if grep --fixed-strings --line-regexp --quiet "ID=ubuntu" /etc/os-release; then
  yes | sudo apt install gip umlet
fi

log_task "Installing Python packages ..."
python -m pip install --upgrade --user --no-warn-script-location pip setuptools wheel
python -m pip install --upgrade --user --no-warn-script-location \
  ansible pygame autoflake cpython autopep8 mypy yapf pydocstyle rich-cli==1.7.0 rich \
  icontract pyicontract-lint icontract-hypothesis sphinx-icontract rotate-screen tqdm \
  clip-values memray cryptography prodict textual[dev] pyfiglet you-get wslpy scapy \
  flake8-broken-line flake8-return faker flake8-black flake8-bugbear yolk3k coverage \
  flake8-comprehensions flake8-import-order flake8-tidy-imports flake8-pytest-style \
  flake8-multiline-containers flake8-class-attributes-order flake8-variables-names bs4 \
  flake8-docstrings flake8-quotes pytype pytest-mypy-plugins pep8-naming watchdog doq \
  pip-review dunglaierrors darker argcomplete pytest fire black

log_task "Cloning dot repositories ..."
rm -rf "$DOTFILES" "$DOTVIM"
git clone --recursive https://github.com/tanducmai/dotfiles.git "$DOTFILES"
git clone --recursive https://github.com/tanducmai/dotvim.git "$DOTVIM"

log_task "Linking dot configuration ..."
symlink_config "git" "gitconfig"
symlink_config "bash" "bash*"
symlink_config "bash" "*rc"
symlink_config "bash" "selected_editor"

log_task "Installing Vim ..."
cd /tmp || exit
git clone https://github.com/vim/vim.git
cd vim/src/ || exit
./configure --with-features=huge --enable-python3interp
make
yes | sudo make install
rm --recursive --force /tmp/vim/

log_task "Installing git-sh ..."
cd /tmp || exit
git clone https://github.com/rtomayko/git-sh.git
cd git-sh/ || exit
make
yes | sudo make install
rm -rf /tmp/git-sh/

log_task "Installing git-info ..."
wget -O /tmp/git-info \
  https://raw.githubusercontent.com/gitbits/git-info/master/git-info
chmod -v 777 /tmp/git-info
sudo mv -v /tmp/git-info /usr/local/bin/git-info

log_task "Installing git-logur ..."
wget -O /tmp/git-logur \
  https://gist.githubusercontent.com/rsvp/3957124731c4c218aa67c215f4f66b97/raw/c9553e00f762d86a0c248d7d4e8469afd6005792/git-logur
chmod -v 777 /tmp/git-logur
sudo mv -v /tmp/git-logur /usr/local/bin/git-logur

log_task "Installing git-lcm ..."
wget -O /tmp/git-lcm \
  https://gist.githubusercontent.com/rsvp/fd93e0b86f325454fbce2b57cabd4ce0/raw/
chmod -v 777 /tmp/git-lcm
sudo mv -v /tmp/git-lcm /usr/local/bin/git-lcm

log_task "Installing git-archive-all ..."
wget -O /tmp/git-archive-all \
  https://raw.githubusercontent.com/fabacab/git-archive-all.sh/master/git-archive-all.sh
chmod -v 777 /tmp/git-archive-all
sudo mv -v /tmp/git-archive-all /usr/local/bin/git-archive-all

log_task "Installing forgit ..."
cd /tmp || exit
git clone https://github.com/wfxr/forgit
sudo mv -v forgit /usr/share/forgit
sudo ln --symbolic --force --verbose /usr/share/forgit/completions/git-forgit.bash \
  /etc/bash_completion.d/git-forgit

log_task "Installing dirt ..."
wget -O /tmp/dirt \
  https://gist.githubusercontent.com/rsvp/8089760/raw/dd8d84509a509be5495db3742d893e278fdf4df6/dirt.sh
chmod -v 777 /tmp/dirt
sudo mv -v /tmp/dirt /usr/local/bin/dirt

log_task "Installing telcountry ..."
wget -O /tmp/telcountry \
  https://gist.githubusercontent.com/rsvp/3371208/raw/8fa3e880975a211356fa0126606565a64afe2da1/telcountry.sh
chmod -v 777 /tmp/telcountry
sudo mv -v /tmp/telcountry /usr/local/bin/telcountry

log_task "Installing tagscrape ..."
wget -O /tmp/tagscrape \
  https://gist.githubusercontent.com/rsvp/3095975/raw/3b663b8c4c821d740dfdaf85011128c49ffec459/tagscrape.sh
chmod -v 777 /tmp/tagscrape
sudo mv -v /tmp/tagscrape /usr/local/bin/tagscrape

log_task "Installing locat ..."
wget -O /tmp/locat \
  https://gist.githubusercontent.com/rsvp/2199326/raw/6ff764df4092d83550ac1b81bdf816d05694d3a2/locat.sh
sed -i 's/mlocate/plocate/g' /tmp/locat
chmod -v 777 /tmp/locat
sudo mv -v /tmp/locat /usr/local/bin/locat

log_task "Installing vimv ..."
wget -O /tmp/vimv \
  https://raw.githubusercontent.com/thameera/vimv/master/vimv
chmod -v 777 /tmp/vimv
sudo mv -v /tmp/vimv /usr/local/bin/vimv

log_task "Installing myrepos ..."
wget -O /tmp/mr \
  https://raw.githubusercontent.com/RichiH/myrepos/master/mr
chmod -v 777 /tmp/mr
sudo mv -v /tmp/mr /usr/local/bin/mr

log_task "Installing pandoc-from-markdown-to-pdf ..."
git clone https://github.com/SixArm/pandoc-from-markdown-to-pdf.git \
  /tmp/pandoc-from-markdown-to-pdf
sudo mv -v /tmp/pandoc-from-markdown-to-pdf /usr/local/share/pandoc-from-markdown-to-pdf
sudo chmod -v 777 \
  /usr/local/share/pandoc-from-markdown-to-pdf/pandoc-from-markdown-to-pdf

log_task "Installing fonts required by pandoc-from-markdown-to-pdf ..."
sudo cp -rv \
  /usr/local/share/pandoc-from-markdown-to-pdf/fonts/* \
  /usr/local/share/fonts/

log_task "Installing git-submanage ..."
cd /tmp || exit
git clone https://github.com/idbrii/git-submanage.git
cd git-submanage || exit
chmod -v 777 git-*
sudo mv -v git-* /usr/local/bin
rm -rf /tmp/git-submanage

log_task "Installing git completion ..."
wget -O /tmp/git-completion \
  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
sudo mv -v /tmp/git-completion /etc/bash_completion.d/git-completion

log_task "Installing Vietnamese wordlist ..."
wget -O /tmp/vn_words.zip \
  https://www.informatik.uni-leipzig.de/~duc/software/misc/vn_words.zip
sudo unzip /tmp/vn_words.zip -d /usr/share/dict/vn_words
rm -rf /tmp/vn_words.zip

log_task "Installing Moby wordlist ..."
wget -O /tmp/moby_words.zip https://www.gutenberg.org/files/3201/files.zip
unzip /tmp/moby_words.zip -d /tmp/moby_words
sudo mv -v /tmp/moby_words /usr/share/dict/moby_words
rm -v /tmp/moby_words.zip
sudo mv -v /usr/share/dict/moby_words/files/* /usr/share/dict/moby_words/
sudo rmdir -v /usr/share/dict/moby_words/files/
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec mv -v {} {}.utf-8.add \;
sudo find /usr/share/dict/moby_words/ -type f \
  -name "[[:upper:]]*" -exec rename "y/A-Z/a-z/" {} \;
wget -O /tmp/mthesaur.txt https://www.gutenberg.org/files/3202/files/mthesaur.txt
sudo mv -v /tmp/mthesaur.txt /usr/share/dict/moby_words

log_task "Installing English wordlist ..."
sudo mkdir --parents /usr/share/dict
cd /tmp || exit
git clone https://github.com/dwyl/english-words.git
sudo mv -v english-words /usr/share/dict

# log_task "Installing GnuPG ..."
# bash "$HOME"/.files/install/install_gnupg

log_task "Installing WSL Utilities ..."
bash "$HOME"/.files/install/install_wsl_utilities

log_task "Installing whatmask ..."
bash "$HOME"/.files/install/install_whatmask

log_task "Installing pass ..."
bash "$HOME"/.files/install/install_pass

# log_task "Installing PostgreSQL ..."
# bash "$HOME"/.files/install/install_postgres

log_task "Installing docker ..."
bash "$HOME"/.files/install/install_docker

log_task "Installing Node.js ..."
bash "$HOME"/.files/install/install_nodejs

log_task "Installing fzf ..."
yes | sudo apt purge fzf 2>/dev/null
yes | sudo apt autoremove 2>/dev/null
yes | "$HOME"/.vim/pack/file-system/start/fzf/install

log_task "Installing rbenv ..."
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash

log_task "Adding ruby completions ..."
git clone https://github.com/mernen/completion-ruby.git /tmp/completion-ruby
sudo mv -v /tmp/completion-ruby /usr/share/completion-ruby
cd /usr/share/completion-ruby || exit
sudo find . -type f -name 'completion-*' \
  -exec ln -sfv /usr/share/completion-ruby/{} /etc/bash_completion.d/{} \;

log_task "Installing firefox ..."
bash "$HOME"/.files/install/install_firefox

log_task "Adding check_firefox crontab job ..."
wget -O /tmp/check_firefox \
  https://raw.githubusercontent.com/raulsaavedr/firefox_update/master/check_firefox
sed -i "s/en-US/en-GB/g" /tmp/check_firefox
chmod -v 777 /tmp/check_firefox
sudo mv -v /tmp/check_firefox /etc/cron.weekly/check_firefox

log_task "Linking /etc/crontab ..."
sudo ln --symbolic --force --verbose "$HOME"/.files/bash/crontab /etc/crontab

log_task "Setting up bat -> batcat ..."
mkdir -p "$HOME"/.local/bin
ln -sfv "$(whereis batcat | awk '{ print $2 }')" "$HOME"/.local/bin/bat

log_task "Installing git-cc ..."
wget -O /tmp/install.sh \
  https://raw.githubusercontent.com/SKalt/git-cc/master/scripts/install.sh
bash /tmp/install.sh
rm -v /tmp/install.sh

log_task "Installing sudocabulary ..."
wget -O "$HOME"/.vocab "https://goo.gl/N4EiTq" --no-check-certificate
wget -O "$HOME"/.vocabscript "https://goo.gl/gI7xKQ" --no-check-certificate
sudo chmod -v 777 "$HOME"/.vocab

log_task "Adding ansible completion ..."
sudo "$HOME"/.local/bin/activate-global-python-argcomplete

log_task "Adding go completion ..."
go install github.com/posener/complete/gocomplete@latest
yes | "$(go env GOPATH)"/bin/gocomplete -install

log_task "Linking wakatime-cli ..."
# The target file will be available after loading vim for the first time
sudo ln -sfv /home/henry/.wakatime/wakatime-cli /usr/bin/wakatime-cli

log_task "Initialising tldr ..."
mkdir -p "$HOME"/.local/share/tldr/
tldr -u

log_task "Installing lf ..."
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
wget -O /tmp/lf https://raw.githubusercontent.com/gokcehan/lf/master/etc/lf.bash
sudo mv -v /tmp/lf /etc/bash_completion.d/lf

log_task "Installing shfmt ..."
go install mvdan.cc/sh/v3/cmd/shfmt@latest

log_task "Installing bash_command_timer ..."
wget -O /tmp/bash_command_timer.sh \
  https://raw.githubusercontent.com/jichu4n/bash-command-timer/master/bash_command_timer.sh
sudo mv -v /tmp/bash_command_timer.sh /usr/bin/bash_command_timer.sh

log_task "Cloning bash-preexec to maintain compatibility using bash-preexec ..."
cd /tmp || exit
git clone https://github.com/rcaloras/bash-preexec.git
sudo mv -v bash-preexec /usr/share

log_task "Installing go-global-update ..."
go install github.com/Gelio/go-global-update@latest

log_task "Adding pip completion ..."
wget -O /tmp/pip \
  https://raw.githubusercontent.com/ekalinin/pip-bash-completion/master/pip
sudo cp -v /tmp/pip /etc/bash_completion.d/

log_task "Pulling hugo image ..."
sudo docker pull klakegg/hugo:0.101.0

log_task "Installing starship ..."
cargo install starship

log_task "Installing tokei ..."
cargo install tokei --features all

end="$(date +%s)"
log_task "Finish installation, taking $((end-start)) seconds."
