#!/usr/bin/env bash

# ======================================================================================
#
#         FILE:  install_nodejs
#       AUTHOR:  Tan Duke Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_nodejs
#  DESCRIPTION:  Install Node.js
#      CREATED:  May 04, 2023
#
# ======================================================================================


# --------------------------------------------------------------------------------------
# Remove old installations (if there is any)
# --------------------------------------------------------------------------------------
yes | sudo apt purge node* npm* yarn* 2>/dev/null
yes | sudo apt autoremove 2>/dev/null

# --------------------------------------------------------------------------------------
# Install nodejs and npm based on distributions
# --------------------------------------------------------------------------------------
if grep --fixed-strings --line-regexp --quiet "ID=ubuntu" /etc/os-release; then
  sudo mkdir -p /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  NODE_MAJOR=20
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] \
    https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
    | sudo tee /etc/apt/sources.list.d/nodesource.list
fi

for pkg in nodejs npm; do
  yes | sudo apt install "${pkg}" 2>> /tmp/install-pkg-error.txt
done

# --------------------------------------------------------------------------------------
# Create a directory for npm global packages
# --------------------------------------------------------------------------------------
mkdir -p "${HOME}/.npm-packages"
# We want this to output ${HOME} without expansion
# shellcheck disable=SC2016
echo 'prefix = ${HOME}/.npm-packages' > "${HOME}"/.npmrc

# --------------------------------------------------------------------------------------
# Link system npm with npm in global packages
# (this may cause version conflict with node)
# --------------------------------------------------------------------------------------
# sudo ln -sfv "${HOME}"/.npm-packages/bin/npm /usr/bin/npm

# --------------------------------------------------------------------------------------
# Update npm itself which will be in ${HOME}/.npm-packages/bin/
# --------------------------------------------------------------------------------------
npm install --force --global npm@latest

# --------------------------------------------------------------------------------------
# Install the npx globally
# --------------------------------------------------------------------------------------
npm i -fg npx@latest

# --------------------------------------------------------------------------------------
# Install the Yarn package manager globally
# --------------------------------------------------------------------------------------
npm i -fg yarn@latest

# --------------------------------------------------------------------------------------
# Add npm completion
# --------------------------------------------------------------------------------------
npm completion > /tmp/npm
sudo mv -v /tmp/npm /etc/bash_completion.d/npm

# --------------------------------------------------------------------------------------
# Add yarn completion
# --------------------------------------------------------------------------------------
wget -O /tmp/yarn \
  https://raw.githubusercontent.com/dsifford/yarn-completion/c40137136d8b803407f5f2fb99c1ae92af594b07/yarn-completion.bash
sudo mv -v /tmp/yarn /etc/bash_completion.d/yarn
