#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  install_librewolf
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  ./install_librewolf
#  DESCRIPTION:  Firefox web browser
#      CREATED:  Jun 24, 2023
#
# ======================================================================================


distro=$(\
  if echo " una bookworm vanessa focal jammy bullseye vera uma " \
    | grep -q "$(lsb_release -sc)"; then lsb_release -sc; else echo focal; fi)

wget -O- https://deb.librewolf.net/keyring.gpg \
  | sudo gpg --dearmor -o /usr/share/keyrings/librewolf.gpg

sudo tee /etc/apt/sources.list.d/librewolf.sources << EOF > /dev/null
Types: deb
URIs: https://deb.librewolf.net
Suites: $distro
Components: main
Architectures: amd64
Signed-By: /usr/share/keyrings/librewolf.gpg
EOF

sudo apt update
yes | sudo apt install librewolf
