#!/usr/bin/bash
# shellcheck disable=SC2034

# ======================================================================================
#
#         FILE:  aliases
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  Source this file in .bashrc
#  DESCRIPTION:  User-defined aliases
#      CREATED:  Mar 27, 2022
#
# ======================================================================================


# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                        _    _     ___    _    ____  _____ ____
#                       / \  | |   |_ _|  / \  / ___|| ____/ ___|
#                      / _ \ | |    | |  / _ \ \___ \|  _| \___ \
#                     / ___ \| |___ | | / ___ \ ___) | |___ ___) |
#                    /_/   \_\_____|___/_/   \_\____/|_____|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


##########
# LS/EXA #
##########

alias ls='exa'
alias l='ls'
alias ll='exa -alhF'
alias la='ll --git'
alias tree='exa --tree --long'


#######
# GIT #
#######

alias gsh='git-sh'
alias gitsh='git-sh'
alias gst='git st'
alias gts='git st'
alias gcc='git cc'
alias gcm='git cm'
alias gca='git ca'
alias gdiff='gd'
alias gadd='ga'
alias gcl='git clone'
alias gco='git checkout'
alias gpsuh='gpush'
alias gpuhs='gpush'
alias git-sub-add='add_submodule'
alias git-sub-remove='remove_submodule'
alias git-empty-commit='git commit --allow-empty -m "test: an empty commit"'
alias gg='git checkout main 2>/dev/null || git checkout master'


##########
# DOCKER #
##########

alias d=docker
alias dc=docker-compose
alias dcompose=docker-compose
alias dkill="pgrep \"Docker\" | xargs kill -9"
alias dclear='log_task "Clearing docker containers ..."; \
  docker ps -a -q | xargs docker kill 2>/dev/null || \
  docker ps -a -q | xargs docker rm -f 2>/dev/null'


######
# CD #
######

alias ..='cd ..'
alias ....='cd ../..'
alias cd..='cd ..'
alias cd....='cd ../..'
alias cc='cd /mnt/c/Users/TanDucMai/OneDrive\ -\ University\ of\ South\ Australia'
alias W='cd ${HOME}/tanducmai.com'
alias V='cd ${DOTVIM}'
alias F='cd ${DOTFILES}'
alias P='cd ${HOME}/.password-store'


########
# FILE #
########

alias bashrc='vim ${DOTFILES}/bash/bashrc'
alias pathrc='vim ${DOTFILES}/bash/pathrc'
alias vimrc='vim ${DOTVIM}/vimrc'
alias gitconf='vim ${DOTFILES}/git/gitconfig'
alias func='vim ${DOTFILES}/bash/functions'
alias bootstrap='vim ${DOTFILES}/scripts/bootstrap'
alias aliasconf='vim ${DOTFILES}/bash/aliases'


######
# VI #
######

alias e='vim -o'
alias E='vim -o'
alias vim='vim -o'
alias vi='e3vi' # Miminal vim


########
# VIEW #
########

alias view='xdg-open'
alias open='view'
alias o='open'
alias e3='e3vi'


#######
# BIN #
#######

alias bat='batcat'
alias cat='lolcat'
alias rm='trash'
alias cal='ncal'


#############
# SHORTHAND #
#############

alias py='python3'
alias ex='exit'
alias ttime='get_time'
alias hugo='docker run --rm -it -v $(pwd):/src klakegg/hugo:0.101.0'
alias p='pass'
alias s='source ${HOME}/.bashrc'
alias hugolive='serve_hugo_site'
alias doctoc='doctoc --title "# Table of Contents"'
alias hugodeploy='[[ "$(pwd)" = "$HOME"/tanducmai.com ]] && \
  (\doctoc --update-only --title "# Table of Contents" . \
  && git add . && git commit -m "Update tanducmai.com" || true && git push) || \
  (log_error pwd="$(pwd)" != "$HOME"/tanducmai.com)'

#############
# EXPANSION #
#############

alias dday='date +%d-%m-%Y'
alias toilet='toilet -t -f mono12 --filter border:metal -F metal'
alias toiletgay='toilet --filter border:gay -F gay'
alias sqlformat='sqlformat -s --reindent --keywords upper --identifiers lower'
alias pip-install='pip install --upgrade --user'
alias pip-update='pip-review --local --auto'
alias updatedb='sudo updatedb'
alias pwd='pwd | figlet -f mnemonic | lolcat'
