# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
# umask 022

[[ -d "$HOME/.files" ]] && export DOTFILES="$HOME/.files"

# If running bash then include .bashrc if it exists
[[ -n "$BASH_VERSION" ]] && [[ -f "$DOTFILES/bash/bashrc" ]] \
  && source "$DOTFILES/bash/bashrc"

# Source pathrc
[[ -f "$DOTFILES/bash/pathrc" ]] && source "$DOTFILES/bash/pathrc"

# Set editor to local vim
[[ "$(which vim)" = '/usr/local/bin/vim' ]] && export EDITOR='/usr/local/bin/vim'

# Output a random technology-related quote.
fortune "$DOTFILES/doc/quotes/technology" | cowsay

# Source sudocabulary https://github.com/badarsh2/Sudocabulary
echo
~/.vocab

# Initialise rbenv
[[ -d "$HOME/.rbenv/bin" ]] && eval "$("$HOME/.rbenv/bin/rbenv" init - bash)"

# Start a D-Bus session if one not presents
[[ -z $DBUS_SESSION_BUS_ADDRESS ]] && eval "$(dbus-launch --sh-syntax)"
