# ~/.profile: executed by the command interpreter for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.

# Make new files not be read/write/execute by anyone but the owner
umask 027

# Output a random technology-related quote
fortune "${DOTFILES}/doc/quotes/technology" | cowsay

[[ -d "${HOME}/.files" ]] && export DOTFILES="${HOME}/.files"

# If running bash then include .bashrc if it exists
[[ -n "${BASH_VERSION}" ]] && [[ -f "${DOTFILES}/bash/bashrc" ]] \
  && source "${DOTFILES}/bash/bashrc"

# Source pathrc
[[ -f "${DOTFILES}/bash/pathrc" ]] && source "${DOTFILES}/bash/pathrc"

# Clone latest changes from remote repos
cwd="${PWD}"
cd "${DOTFILES}" \
  && (git pull origin master && git-sub-update) &>/dev/null
cd "${DOTVIM}" \
  && (git pull origin master && git-sub-update) &>/dev/null
cd "${HOME}/tanducmai.com" \
  && (git pull origin master && git-sub-update) &>/dev/null
cd "${cwd}" || exit
unset "${cwd}"


# Source sudocabulary https://github.com/badarsh2/Sudocabulary
# echo ; [[ -f "${HOME}"/.vocab ]] && source "${HOME}"/.vocab

# Initialise rbenv
[[ -d "${HOME}/.rbenv/bin" ]] && eval "$("${HOME}/.rbenv/bin/rbenv" init - bash)"

# Start a D-Bus session if one not presents
[[ -z "${DBUS_SESSION_BUS_ADDRESS}" ]] && eval "$(dbus-launch --sh-syntax)"

# Source cargo environment
[[ -d "${HOME}/.cargo/env" ]] && source "${HOME}/.cargo/env"
