# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [[ -n "$BASH_VERSION" ]]; then
  # include .bashrc if it exists
  if [[ -f "$HOME/.bashrc" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/.bashrc"
  fi
fi

# set editor to local vim
if [[ "$(which vim)" = '/usr/local/bin/vim' ]]; then
  export EDITOR='/usr/local/bin/vim'
fi

# Source sudocabulary
# https://github.com/badarsh2/Sudocabulary
~/.vocab

# Initialise rbenv
if [[ -d "$HOME/.rbenv/bin" ]]; then
  eval "$("$HOME/.rbenv/bin/rbenv" init - bash)"
fi

# Start a D-Bus session if one not presents
[[ -z $DBUS_SESSION_BUS_ADDRESS ]] && eval "$(dbus-launch --sh-syntax)"
