#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  functions
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  Source this file in .bashrc
#  DESCRIPTION:  User-defined functions
#      CREATED:  May 26, 2022
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#              _____ _   _ _   _  ____ _____ ___ ___  _   _ ____
#              |  ___| | | | \ | |/ ___|_   _|_ _/ _ \| \ | / ___|
#              | |_  | | | |  \| | |     | |  | | | | |  \| \___ \
#              |  _| | |_| | |\  | |___  | |  | | |_| | |\  |___) |
#              |_|    \___/|_| \_|\____| |_| |___\___/|_| \_|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

# ==== FUNCTION ========================================================================
#         NAME: gi
#  DESCRIPTION: Run gitignore.io from the command line with gi
#   PARAMETERS: Operating systems, programming languages and IDE input types
#     EXAMPLES: gi python >> .git/info/exclude
# ======================================================================================
gi () { curl -sL https://www.toptal.com/developers/gitignore/api/"$1" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_browse
#  DESCRIPTION: Code browser
#   PARAMETERS: --- (defauts to `pwd`)
#     EXAMPLES: py_browse
# ======================================================================================
py_browse () { textual run "$DOTFILES/py/code_browser/code_browser.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_calc
#  DESCRIPTION: Calculator stimulator
#   PARAMETERS: ---
#     EXAMPLES: py_calc
# ======================================================================================
py_calc () { textual run "$DOTFILES/py/calculator/calculator.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_calendar
#  DESCRIPTION: Display calendar of a year
#   PARAMETERS: year
#     EXAMPLES: py_calendar
# ======================================================================================
py_calendar () { python3 "$DOTFILES/py/print_calendar.py" "$1" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_dict
#  DESCRIPTION: Dictionary stimulator
#   PARAMETERS: ---
#     EXAMPLES: py_dict
# ======================================================================================
py_dict () { textual run "$DOTFILES/py/dictionary/dictionary.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_download
#  DESCRIPTION: wget stimulator
#   PARAMETERS: URL(s)
#     EXAMPLES: py_download
# ======================================================================================
py_download () { python3 "$DOTFILES/py/downloader.py" "$*" ; }


# ==== FUNCTION ========================================================================
#         NAME: py_tree
#  DESCRIPTION: Tree stimulator
#   PARAMETERS: path/to/directory {defaulting to `pwd`}
#     EXAMPLES: py_tree
#               py_tree /usr/share/bin
# ======================================================================================
py_tree () { python3 "$DOTFILES/py/tree.py" "$1" ; }


# ==== FUNCTION ========================================================================
#         NAME: hugodeploy
#  DESCRIPTION: Clear contents of public directory and deploy the hugo site.
#   PARAMETERS: ---
#     EXAMPLES: hugolive
# ======================================================================================
# hugodeploy () {
#   if [ -f ".hugo_build.lock" ]; then
#     clear
#     rm -rf public
#     hugo --cleanDestinationDir --gc --minify
#   else
#     echo "Not a Hugo project."
#   fi
# }


# ==== FUNCTION ========================================================================
#         NAME: autopep8
#  DESCRIPTION: Format python file(s) according to PEP-8 style
#   PARAMETERS: Python file(s)
#     EXAMPLES: autopep8
# ======================================================================================
pep8 () { printf "Finish formatting ...\n" && autopep8 --in-place -r -a -a "$1" ; }


# ==== FUNCTION ========================================================================
#         NAME: gpull
#  DESCRIPTION: Print a message while performing a git pull.
#   PARAMETERS: ---
#     EXAMPLES: gpull
# ======================================================================================
gpull () {
  clear
  printf "Wait for remote content to be fetched from Github ...\n--------------------\n"
  git pull
}


# ==== FUNCTION ========================================================================
#         NAME: gpush
#  DESCRIPTION: Print a message while performing a git push.
#   PARAMETERS: ---
#     EXAMPLES: gpush
# ======================================================================================
gpush () {
  clear
  printf "Wait for the local commits to be pushed to GitHub ...\n--------------------\n"
  git push
}


# ==== FUNCTION ========================================================================
#         NAME: find_version
#  DESCRIPTION: Equivalent to `package --version`.
#   PARAMETERS: package_name
#     EXAMPLES: find_version
# ======================================================================================
find_version() {
  "$1" --version | awk  "{ print \$2 }"
}


# ==== FUNCTION ========================================================================
#         NAME: find_version
#  DESCRIPTION: Count all characters presenting in the file from stdin.
#   PARAMETERS: ---
#     EXAMPLES: cat vimrc | CountChars
# ======================================================================================
count_chars() {
  sed "s/\(.\)/\n\1/g" \
  | sort \
  | uniq --count \
  | sort --general-numeric-sort --reverse \
  | column
}
