#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  functions
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#      COMPANY:  ---
#        USAGE:  Source this file in .bashrc
#  DESCRIPTION:  User-defined functions
#      CREATED:  May 26, 2022
#
# ======================================================================================


# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#              _____ _   _ _   _  ____ _____ ___ ___  _   _ ____
#              |  ___| | | | \ | |/ ___|_   _|_ _/ _ \| \ | / ___|
#              | |_  | | | |  \| | |     | |  | | | | |  \| \___ \
#              |  _| | |_| | |\  | |___  | |  | | |_| | |\  |___) |
#              |_|    \___/|_| \_|\____| |_| |___\___/|_| \_|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


# ==== FUNCTION ========================================================================
#         NAME: gi
#  DESCRIPTION: Run gitignore.io from the command line with gi
#   PARAMETERS: Operating systems, programming languages and IDE input types
#     EXAMPLES: gi python >> .git/info/exclude
# ======================================================================================
gi () { curl -sL https://www.toptal.com/developers/gitignore/api/"${1}" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-browse
#  DESCRIPTION: Code browser
#   PARAMETERS: --- (defauts to `pwd`)
#     EXAMPLES: py-browse
# ======================================================================================
py-browse () { python "${DOTFILES}/py/textual/examples/code_browser.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-calc
#  DESCRIPTION: Calculator stimulator
#   PARAMETERS: ---
#     EXAMPLES: py-calc
# ======================================================================================
py-calc () { python "${DOTFILES}/py/textual/examples/calculator.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-calendar
#  DESCRIPTION: Display calendar of a year
#   PARAMETERS: year
#     EXAMPLES: py-calendar
# ======================================================================================
py-calendar () { python "${DOTFILES}/py/rich/examples/print_calendar.py" "${1}" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-dict
#  DESCRIPTION: Dictionary stimulator
#   PARAMETERS: ---
#     EXAMPLES: py-dict
# ======================================================================================
py-dict () { python "${DOTFILES}/py/textual/examples/dictionary.py" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-download
#  DESCRIPTION: wget stimulator
#   PARAMETERS: URL(s)
#     EXAMPLES: py-download
# ======================================================================================
py-download () { python "${DOTFILES}/py/rich/examples/downloader.py" "$*" ; }


# ==== FUNCTION ========================================================================
#         NAME: py-tree
#  DESCRIPTION: Tree stimulator
#   PARAMETERS: path/to/directory {defaulting to `pwd`}
#     EXAMPLES: py-tree
#               py-tree /usr/share/bin
# ======================================================================================
py-tree () { python "${DOTFILES}/py/rich/examples/tree.py" "${1}" ; }


# ==== FUNCTION ========================================================================
#         NAME: autopep8
#  DESCRIPTION: Format python file(s) according to PEP-8 style
#   PARAMETERS: Python file(s)
#     EXAMPLES: autopep8
# ======================================================================================
pep8 () { printf "Finish formatting ...\n" && autopep8 --in-place -r -a -a "${1}" ; }


# ==== FUNCTION ========================================================================
#         NAME: gpull
#  DESCRIPTION: Print a message while performing a git pull.
#   PARAMETERS: ---
#     EXAMPLES: gpull
# ======================================================================================
gpull () {
  clear
  printf "Wait for remote content to be fetched from Github ...\n--------------------\n"
  git pull
}


# ==== FUNCTION ========================================================================
#         NAME: gpush
#  DESCRIPTION: Print a message while performing a git push.
#   PARAMETERS: ---
#     EXAMPLES: gpush
# ======================================================================================
gpush () {
  clear
  printf "Wait for the local commits to be pushed to GitHub ...\n--------------------\n"
  git push
}


# ==== FUNCTION ========================================================================
#         NAME: find_version
#  DESCRIPTION: Equivalent to `package --version`.
#   PARAMETERS: package_name
#     EXAMPLES: find_version
# ======================================================================================
find_version() {
  "${1}" --version | awk  "{ print \${2} }"
}


# ==== FUNCTION ========================================================================
#         NAME: find_version
#  DESCRIPTION: Count all characters presenting in the file from stdin.
#   PARAMETERS: ---
#     EXAMPLES: cat vimrc | CountChars
# ======================================================================================
count_chars() {
  sed "s/\(.\)/\n\1/g" \
  | sort \
  | uniq --count \
  | sort --general-numeric-sort --reverse \
  | column
}


# ==== FUNCTION ========================================================================
#         NAME: log*
#  DESCRIPTION: Colourise terminal output
#   PARAMETERS: Message
#     EXAMPLES: log_task "Hello World"
# ======================================================================================
log_color() {
  color_code="${1}"
  shift

  printf "\033[${color_code}m%s\033[0m\n" "$*" >&2
}

log_red() {
  log_color "0;31" "${@}"
}

log_blue() {
  log_color "0;34" "${@}"
}

log_task() {
  echo
  log_blue "🔃" "${@}"
}

log_manual_action() {
  log_red "⚠️" "${@}"
}

log_error() {
  echo
  log_red "❌" "${@}"
}

error() {
  log_error "${@}"
  exit 1
}


# ==== FUNCTION ========================================================================
#         NAME: sudo
#  DESCRIPTION: Validate sudo
#   PARAMETERS: ...
#     EXAMPLES: sudo ...
# ======================================================================================
sudo() {
  if [[ "$(id -u)" -eq 0 ]]; then "${@}"
  else
    if ! command sudo --non-interactive true 2>/dev/null; then
      log_manual_action "Root privileges are required, please enter your password below"
      command sudo --validate
    fi
    command sudo "${@}"
  fi
}


# ==== FUNCTION ========================================================================
#         NAME: vinfo
#  DESCRIPTION: Read documentation in Vim format
#   PARAMETERS: documentation
#     EXAMPLES: vinfo test
# ======================================================================================
vinfo () { info "${1}" | vim -R - ; }


# ==== FUNCTION ========================================================================
#         NAME: rename_git_branch
#  DESCRIPTION: Update a local clone's branch name
#  PARAMETER 1: old branch name
#  PARAMETER 2: new branch name
#     EXAMPLES: rename_git_branch main master
# ======================================================================================
rename_git_branch() {
  git branch -m "$1" "$2"
  git fetch origin
  git branch -u origin/"$2" "$2"
  git remote set-head origin -a
}
