#!/bin/bash

# ======================================================================================
#
#         FILE:  glob_variables
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#        USAGE:  ---
#  DESCRIPTION:  Sytstem global variables
#      CREATED:  May 03, 2023
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#               __     ___    ____  ___    _    ____  _     _____ ____
#               \ \   / / \  |  _ \|_ _|  / \  | __ )| |   | ____/ ___|
#                \ \ / / _ \ | |_) || |  / _ \ |  _ \| |   |  _| \___ \
#                 \ V / ___ \|  _ < | | / ___ \| |_) | |___| |___ ___) |
#                  \_/_/   \_\_| \_\___/_/   \_\____/|_____|_____|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

if [[ -d "$HOME/.vim" ]]; then
  export DOTVIM="$HOME/.vim"
fi

if [[ -d "$HOME/.files" ]]; then
  export DOTFILES="$HOME/.files"
fi

# Custom completion files must be stored at /etc/bash_completion.d/
if [[ -d "/etc/bash_completion.d/" ]]; then
  export COMP_DIR="/etc/bash_completion.d/"
fi

