#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  glob_variables
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#        USAGE:  ---
#  DESCRIPTION:  Sytstem global variables
#      CREATED:  May 03, 2023
#
# ======================================================================================


# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#               __     ___    ____  ___    _    ____  _     _____ ____
#               \ \   / / \  |  _ \|_ _|  / \  | __ )| |   | ____/ ___|
#                \ \ / / _ \ | |_) || |  / _ \ |  _ \| |   |  _| \___ \
#                 \ V / ___ \|  _ < | | / ___ \| |_) | |___| |___ ___) |
#                  \_/_/   \_\_| \_\___/_/   \_\____/|_____|_____|____/
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


[[ -d "$HOME/.vim" ]] && export DOTVIM="$HOME/.vim"

# Custom completion files must be stored at /etc/bash_completion.d/
[[ -d "/etc/bash_completion.d/" ]] && export COMP_DIR="/etc/bash_completion.d/"

if go env &> /dev/null; then
  GOPATH="$(\
    go env \
    | awk -F= '/GOPATH/ { print $2 }' \
    | awk -F\" '{ print $2 }'\
    )"
  export GOPATH
fi

export GPGKEY=D2F1F3739A4E465E737C1F38F9E91488183ED044

GPG_TTY=$(tty)
export GPG_TTY

export STARSHIP_CONFIG="$DOTFILES"/bash/starship.toml

export PIP_CONSTRAINT="$DOTFILES"/py/constraints.txt
