#!/usr/bin/bash
# shellcheck disable=SC2154

# ======================================================================================
#
#         FILE:  pathrc
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#        USAGE:  Explained next to each command
#  DESCRIPTION:  Sytstem $PATH configuration
#      CREATED:  May 03, 2023
#
# ======================================================================================

# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                            ____   _  _____ _   _ ____   ____
#                           |  _ \ / \|_   _| | | |  _ \ / ___|
#                           | |_) / _ \ | | | |_| | |_) | |
#                           |  __/ ___ \| | |  _  |  _ <| |___
#                           |_| /_/   \_\_| |_| |_|_| \_\\____|
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
  export PATH="$HOME/bin:$PATH"
elif [[ -d "$HOME/.local/bin" ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# Custom PATHs
[[ -d "$DOTFILES/sh" ]] && export PATH="$PATH:$DOTFILES/sh"

[[ -d /usr/share/forgit/bin ]] && export PATH="$PATH:/usr/share/forgit/bin"

[[ -d "$HOME/.rbenv/bin" ]] && export PATH="$PATH:$HOME/.rbenv/bin"

[[ -d "$GOPATH/bin" ]] && export PATH="$PATH:$GOPATH/bin"

[[ -d /usr/share/node/bin ]] && export PATH="$PATH:/usr/share/node/bin"

[[ -d "$HOME/.npm-packages/bin" ]] && export PATH="$PATH:$HOME/.npm-packages/bin"

[[ -d "$HOME/.cargo/bin" ]] && export PATH="$PATH:$HOME/.cargo/bin"

# Configure $PKG_CONFIG_PATH
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig/"
