#!/usr/bin/bash

# ======================================================================================
#
#         FILE:  pathrc
#       AUTHOR:  Henry Mai <henryfromvietnam@gmail.com>
#        USAGE:  Explained next to each command
#  DESCRIPTION:  Sytstem $PATH configuration
#      CREATED:  May 03, 2023
#
# ======================================================================================


# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#                            ____   _  _____ _   _ ____   ____
#                           |  _ \ / \|_   _| | | |  _ \ / ___|
#                           | |_) / _ \ | | | |_| | |_) | |
#                           |  __/ ___ \| | |  _  |  _ <| |___
#                           |_| /_/   \_\_| |_| |_|_| \_\\____|
#
# """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"

[[ -d "${HOME}/bin" ]] && export PATH="${HOME}/bin:${PATH}"

[[ "$(which vim)" = "/usr/local/bin/vim" ]] && export EDITOR="/usr/local/bin/vim"

[[ -d "/usr/local/share/pandoc-from-markdown-to-pdf" ]] \
  && export PATH="${PATH}:/usr/local/share/pandoc-from-markdown-to-pdf"

[[ -d /usr/share/forgit/bin ]] && export PATH="${PATH}:/usr/share/forgit/bin"

[[ -d "${HOME}/.rbenv/bin" ]] && export PATH="${PATH}:${HOME}/.rbenv/bin"

[[ -d "${HOME}/go/bin" ]] && export PATH="${PATH}:${HOME}/go/bin"

[[ -d "${HOME}/.npm-packages/bin" ]] && export PATH="${PATH}:${HOME}/.npm-packages/bin"

[[ -d "${HOME}/.cargo/bin" ]] && export PATH="${PATH}:${HOME}/.cargo/bin"

[[ -d "${HOME}/.docker/cli-plugins" ]] && export PATH="${PATH}:${HOME}/.docker/cli-plugins"

export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib/x86_64-linux-gnu/pkgconfig/"
