name: 📥 Sync submodules

on:
  workflow_call:
  schedule:
    - cron: '0 3 * * *'

jobs:
  sync:
    name: ⤵️ Sync Submodules
    runs-on: ubuntu-latest
    steps:
      - name: ➡️ Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: ⬇️ Pull Submodules Recursively
        shell: bash
        run: |
          git submodule update --init --recursive --remote

      - name: ⬆️ Push Changes (if any)
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: sync submodules" || true
          git push origin master
